<div class="central-home">

<div class="tutorial">


<div class="tutorial-title">What is TRADUXIO?&nbsp;</div>

<DIV class="nutshell">
<i>Traduxio</i> in a nutshell :
<UL class="hyphen">
<LI>free</LI>
<LI>open source</LI>
<LI>web based</LI>
<LI>collaborative</LI>
<LI>focus on cultural (non commercial, non repetitive) texts. </LI>
<LI>developed with innovative technology (new Translation Memory device)</LI>
</UL>
</DIV>


<div class="tutorial-text">

<P><i>Traduxio</i> is a<I>computer assisted tool</I> and a <I>online workbench</I> intended to promote translation through and on the Web.</P>
<?php /*<P>In the long run, <I>Traduxio</I> should also promote the diversification of language learning and a reappraisal of translation activities, especially in the field of research-making.</P> */ ?>
<P>Designed by the non-profit organization Zanchin, and developed with the technical
support of the <a href="http://tech-cico.utt.fr">Tech-Cico laboratory</a> of the <A HREF="http://www.utt.fr">University of Technology of Troyes</A> (France) and the help of other <A HREF="http://sourceforge.net/apps/wordpress/traduxio/2009/12/02/partenaires/">partners</A>,
 <I>Traduxio</I> employs the most innovative solutions to foster cultural exchange and the preservation of the world’s linguistic diversity. </P>
<P>This new collaborative software, directly inspired by Web 2.0 spirit, has the vocation to become a major asset for current efforts to foster cultural exchange and the preservation of the world’s linguistic diversity.</P>
<P>In the long run, the tool should also encourage the diversification of language learning and a reappraisal of translation activities, especially in the field of research-making.</P>
<P>Its potential has already been recognized and <I>Traduxio</I> is being currently supported by the Unesco and the Organisation Internationale de la Francophonie.</P>
<P>To understand how <I>Traduxio</I> actually works and what it can do, check the <a href="<?php echo $this->makeUrl("/index/tutorial/"); ?>">tutorial</a>.</P>


</div>
<div class="tutorial-text">

<h3><I>Traduxio</I>, applying original solutions to translation</h3>
<UL>
	<LI>Whereas 	traditional Translation Memory device are limited to two languages
	(source/target), <I>Traduxio</I> enables the comparison of different versions of the same text. A translated text is actually not considered an independent segment, but a <I>version</I>	of the initial text in another language. </LI>
	<LI><I>Traduxio</I>	offers a better management of the translation context, thanks to a contextualized classification of the source (i.e. classification of the text according to the history, genre, author, etc.). </LI>
</UL>
</div>
<div class="tutorial-text">

<h3><i>Traduxio</i> to whom ?</h3>
<P>As a mechanism of general interest, grounded on a logic of collaboration and mutualization (gradual feeding of the database), <i>Traduxio</i> is easy to use and available to a very broad audience:</P>
<UL>
	<LI>It can be used by
	translators, researchers, teachers, students, and all those who use
	language and need translation for broadening the impact of their work and
	activities.</LI>
	<LI>Likewise, NGOs,
	international organizations, research institutions, think
	tanks, schools, stage performers reviewing translations for a
	theatre play, and all those who may come across a need for
	translation are <i>Traduxio</i>’s potential users. </LI>
</UL>
</div>
<div class="tutorial-text">

<h3>Translating
with <I>Traduxio</i>: Legal
and Practical aspects</h3>
<UL>
	<LI><I>Traduxio</I>	as a workbench </LI>
</UL>
<P><I>Traduxio</I> is <i>not</i> designed to perform any publishing or editorial functions, but rather
to work as a digital workbench and network connecting
users/translators worldwide. Translations carried out using <i>Traduxio</I>
are thus not intended to be published or printed by the web-service
itself – although authors may personally chose to do so. </P>
<UL>
	<LI><I>Traduxio</I>	as a “commons”</LI>
</UL>
<P>All content provided
by users are integrated to the Translation Memory, which is the
foundation and the real differential of the tool. Following
the logic of mutualization on which it is based, <I>Traduxio</I>’s
ultimate goal is to become a “commons” (like Creative Commons or
Wikimedia Commons) on a non-profit basis.</P>
<UL>
	<LI>Protecting translators’
	work while promoting the ‘common good’</LI>
</UL>
<P>The non-commercial
and ‘communitarian’ dimension of the tool do <I>not</I>
imply that the resulting translations will belong to the public
domain. On the contrary, each translator will be given the
possibility to tag its creation with a legal license of his choice
(e.g. Creative Commons license). The range of rights’ attribution
goes from the public domain to full copyright (in which case, a ‘fair use device’ shall be used for quotations from the database). Users will be however
encouraged to choose at least an attribution license. </P>
<P>Attribution of authority over
translations is indeed important since the re-utilization of “memory
matching” depends on the identification of the author of a given
semantic creation. Frequent users could thus benefit from a form of
public and non-financial recognition (a system of “points”),
which eventually might turn into a sort of professional reputation.</P>
</div>
<?php /*<h3>Challenge</h3>
<P>The main challenge in setting up this
kind of web-based tool is the establishment (feeding) of an initial
database upon which the Translation Memory system can properly run.
This particular aspect of the software makes it considerably
dependent upon the existence of an important community of
users/collaborators from the beginning.
</P>
<P>Nevertheless, the multiple advantages
offered by the software should greatly help persuading potential
translators to contribute to the initial feeding of the database,
when collaboration is most needed.</P>
*/ ?>
</div>
</div>
<?php $this->page_title=__("PAGETITLE_About Traduxio"); ?>
