<div class="central-home">
<div id="margin">

<div id="page-title"><?php echo __("Report an on-line abuse"); ?></div>

<?php if ($this->sent) : ?>
<div class="comment">
<?php echo __("Your abuse report has been successfully sent; thank you for your help.");?>
<br /><br /><?php echo __("The %1\$s team.","<i>Traduxio</i>"); ?>
</div>
<br /><div class="comment"><a href="<?php echo $this->backUrl; ?>"><?php echo __("Continue")?></a></div>
<?php else :?>
<?php if ($this->error) : ?>
<div class="comment"><?php echo __("We encountered an error sending your message. Here is the error message : %1\$s.
Sorry for the inconvenience, we're trying hard to fix it.","<i>".$this->error."</i>")?>
<br /><?php echo __("The %1\$s team.","<i>Traduxio</i>"); ?>
</div>
<?php else: ?>
<?php echo $this->form; ?>
<?php endif; ?><?php endif; ?>
<?php $this->page_title=__("PAGETITLE_Copyright"); ?>
</div>
</div>


