<?php ?>
 
<div class="central-home">

<div class="tutorial">

<div class="tutorial-title"><?php echo __("Frequently Asked Questions");?></div>
<ol>
<div class="tutorial-text">
<div class="question"><li><?php echo __("FAQuestion1") ?></li></div>
<div class="answer">
<?php echo __("FAQanswer1",'<a href="http://traduxio.sourceforge.net/" target="_blank">','</a>');?>
</div>
</div>

<div class="tutorial-text">
<div class="question"><li><?php echo __("FAQuestion2");?></li></div>
<div class="answer"><?php echo __("FAQanswer2",'<a href="http://sourceforge.net/apps/trac/traduxio/wiki/HowTo" target="_blank">','</a>');?></div>
</div>


<div class="tutorial-text">
<div class="question"><li>
<?php echo __("FAQuestion3");?></li></div>
<div class="answer"><?php echo __("FAQanswer3");?></div>
</div>

<div class="tutorial-text">
<div class="question"><li>
<?php echo __("FAQuestion4");?></li></div>
<div class="answer">
<?php echo __("FAQanswer4",'<a href="<?php echo $this->makeUrl(\'/index/register\'); ?>">','</a>','<a href="<?php echo $this->makeUrl(\'/index/index\'); ?>">','</a>');?></div>
</div>


<div class="tutorial-text">
<div class="question"><li>
<?php echo __("FAQuestion5");?></li></div>
<div class="answer">
<?php echo __("FAQanswer5");?></div>
</div>


<div class="tutorial-text">
<div class="question"><li>
<?php echo __("FAQuestion6");?></li></div>
<div class="answer">
<?php echo __("FAQanswer6");?></div>
</div>


<div class="tutorial-text">
<div class="question"><li>
<?php echo __("FAQuestion7");?></li></div>
<div class="answer">
<?php echo __("FAQanswer7");?></div>
</div>


<div class="tutorial-text">
<div class="question"><li>
<?php echo __("FAQuestion8");?></li></div>
<div class="answer">
<?php echo __("FAQanswer8");?></div>
</div>


<div class="tutorial-text">
<div class="question"><li>
<?php echo __("FAQuestion9");?></li></div>
<div class="answer">
<?php echo __("FAQanswer9");?></div>
</div>


<div class="tutorial-text">
<div class="question"><li>
<?php echo __("FAQuestion10");?></li></div>
<div class="answer">
<?php echo __("FAQanswer10");?></div>
</div>


<div class="tutorial-text">
<div class="question"><li>
<?php echo __("FAQuestion11");?></li></div>
<div class="answer">
<?php echo __("FAQanswer11");?></div>
</div>

<div class="tutorial-text">
<div class="question"><li>
<?php echo __("FAQuestion12");?></li></div>
<div class="answer">
<?php echo __("FAQanswer12");?></div>
</div>


<div class="tutorial-text">
<div class="question"><li>
<?php echo __("FAQuestion13");?></li></div>
<div class="answer">
<?php echo __("FAQanswer13");?></div>
</div>


<div class="tutorial-text">
<div class="question"><li>
<?php echo __("FAQuestion14");?></li></div>
<div class="answer">
<?php echo __("FAQanswer14");?></div>
</div>


</ol>

</div>
</div>

<?php $this->page_title=__('Frequently Asked Questions'); ?>
