<div class="central-home">

<div class="tutorial">

<div class="tutorial-title">Frequently Asked Questions&nbsp;</div>
<ol>
<div class="tutorial-text">
<div class="question"><li>What is TraduXio?</li></div>
<div class="answer">
TraduXio is a participative platform for cultural texts translators.
<br> For a detailed description, visit the <a href="http://sourceforge.net/apps/trac/traduxio/wiki" target="_blank">official page on SourceForge</a>.</div>
</div>

<div class="tutorial-text">
<div class="question"><li>How can I use TraduXio?</li></div>
<div class="answer">You can use TraduXio depositing some texts and translating them...</div>
</div>

<div class="tutorial-text">
<div class="question"><li>Should I register? How can I do it?</li></div>
<div class="answer">In order to completely use TraduXio (deposit and translating texts,...) you must be registered.
<br>To register, click on the <a href="<?php echo $this->makeUrl('/index/register'); ?>">"Register"</a> menu in the <a href="<?php echo $this->makeUrl('/index/index'); ?>">homepage</a>.</div>
</div>
</ol>

</div>
</div>

<?php $this->page_title=__('Frequently Asked Questions'); ?>
