<?php ?>
 
<div class="central-home">

<div class="tutorial">

<div class="tutorial-title"><?php echo __("Frequently Asked Questions");?></div>


<ol class="tutorial-text">

<li class="question"><?php echo __("FAQuestion1") ?>
<div class="answer">
<?php echo __("FAQanswer1",'<a href="http://traduxio.sourceforge.net/" target="_blank">','</a>');?>
</div></li>

<li class="question"><?php echo __("FAQuestion2");?>
<div class="answer">
<?php echo __("FAQanswer2",'<a href="http://sourceforge.net/apps/trac/traduxio/wiki/HowTo" target="_blank">','</a>');?>
</div></li>

<li class="question">
<?php echo __("FAQuestion3");?>
<div class="answer"><?php echo __("FAQanswer3");?></div>
</li>

<li class="question">
<?php echo __("FAQuestion4");?>
<div class="answer">
<?php echo __("FAQanswer4",'<a href="<?php echo $this->makeUrl(\'/index/register\'); ?>">','</a>','<a href="<?php echo $this->makeUrl(\'/index/index\'); ?>">','</a>');?>
</div></li>

<li class="question">
<?php echo __("FAQuestion5");?>
<div class="answer"><?php echo __("FAQanswer5");?></div>
</li>

<li class="question">
<?php echo __("FAQuestion6");?>
<div class="answer"><?php echo __("FAQanswer6");?></div>
</li>

<li class="question">
<?php echo __("FAQuestion7");?>
<div class="answer"><?php echo __("FAQanswer7");?></div>
</li>

<li class="question">
<?php echo __("FAQuestion8");?>
<div class="answer"><?php echo __("FAQanswer8");?></div>
</li>

<li class="question">
<?php echo __("FAQuestion9");?>
<div class="answer"><?php echo __("FAQanswer9");?></div>
</li>

<li class="question">
<?php echo __("FAQuestion10");?>
<div class="answer"><?php echo __("FAQanswer10");?></div>
</li>

<li class="question">
<?php echo __("FAQuestion11");?>
<div class="answer"><?php echo __("FAQanswer11");?></div>
</li>

<li class="question">
<?php echo __("FAQuestion12");?>
<div class="answer"><?php echo __("FAQanswer12");?></div>
</li>

<li class="question">
<?php echo __("FAQuestion13");?>
<div class="answer"><?php echo __("FAQanswer13");?></div>
</li>

<li class="question">
<?php echo __("FAQuestion14");?>
<div class="answer"><?php echo __("FAQanswer14");?></div>
</li>


</ol>

</div>
</div>

<?php $this->page_title=__('Frequently Asked Questions'); ?>
