<?php $phrase = __("frase_en"); $logo = __("logoEN");  ?> 
<div id="index"> 
  <a href="<?php echo $this->makeUrl('/index/register'); ?>"><div class="indexopt"><?php echo __("Register"); ?></div></a>
  <a href="http://traduxio.community.hypertopic.org/" target="_blank" ><div class="indexopt"><?php echo __("Invite"); ?></div></a>
  <a href="<?php echo $this->makeUrl('/index/faq'); ?>"><div class="indexopt"><?php echo __("FAQ"); ?></div></a>
  <a href="http://sourceforge.net/apps/trac/traduxio/wiki" target="_blank"><div class="indexopt"><?php echo __("About Traduxio"); ?></div></a>
  <a href="http://sourceforge.net/apps/trac/traduxio/wiki/HowTo" target="_blank"><div class="indexopt"><?php echo __("Help"); ?></div></a>
</div>
<div id="traduxio_logo">
    <div><img src="<?php echo $this->makeUrl('/images/toc.png') ?>"></div>
    <div><img src="<?php echo $this->makeUrl('/images/'.$phrase.'.png') ?>"></div>
</div>

<div id="logo_cip"><img src="<?php echo $this->makeUrl('/images/'.$logo.'.png') ?>"></div>

<?php $image = __("indexlogoEN"); ?>
