<?php $traduxio = __("traduxio_en"); $logo = __("logoEN");  ?> 
<div id="index"> 
  <a href="<?php echo $this->makeUrl('/index/register'); ?>"><div class="indexopt"><?php echo __("Register"); ?></div></a>
  <a href="http://traduxio.community.hypertopic.org/" target="_blank" ><div class="indexopt"><?php echo __("Invite"); ?></div></a>
  <a href="<?php echo $this->makeUrl('/index/faq'); ?>"><div class="indexopt"><?php echo __("FAQ"); ?></div></a>
  <a href="http://sourceforge.net/apps/trac/traduxio/wiki" target="_blank"><div class="indexopt"><?php echo __("About Traduxio"); ?></div></a>
</div>
<div id="traduxio_logo"><img src="<?php echo $this->makeUrl('/images/'.$traduxio.'.png') ?>"></div>

<div id="logo_cip"><img src="<?php echo $this->makeUrl('/images/'.$logo.'.png') ?>"></div>

<?php $image = __("indexlogoEN"); ?>
