<?php $this->layout()->setLayout('jslayout');?>

tdxio.i18n = {
	'hi':"<?php echo __("hello"); ?>",
	'showtags' : "<?php echo __("Show tags");?>",
	'hidetags' : "<?php echo __("Hide tags");?>",
	'clicktoedit'  : "<?php echo __("Click to edit");?>",
	'want2delete'  : "<?php echo __("WARNING! Deletion is a definitive choice! Are you SURE you want to delete this text?");?>",
	'missingpriv'  : "<?php echo ($this->isMember)?__("You're not allowed to do this. Ask permissions to the text's owner"):__("You're not allowed to do this. Please login");?>",
	'notehint'	   : "<?php echo __("Click on a sentence to insert a tag/note for it");?>",
	'HTmessage'    : "<?php echo __("You can't delete this text because it has some translations. Delete its translations first.");?>",
	'askConfirm'   : "<?php echo __("WARNING! Deletion is a definitive choice! Are you SURE you want to delete this text?");?>",
	'cuthere'      : "<?php echo __("Cut here");?>",
	'mergehere'    : "<?php echo __("Merge here");?>",
	'createtrsl'   : "<?php echo __("Create a translation");?>",
	'anonymous'    : "<?php echo __("Anonymous");?>",
	'notitle'      : "<?php echo __("No title");?>",
};
