<?php $this->page_title="Tutorial"; ?>
<div class="central-home">
<!--<div id="black-border">-->
<div id="tutorial">
<h1 LANG="en-GB" CLASS="western" STYLE="margin-bottom: 0cm">Welcome to
the Traduxio sandbox&nbsp;!</h1>
<div id="tutorial-text">
<P LANG="en-GB" CLASS="western" STYLE="margin-bottom: 0cm"><BR>
</P>
<P LANG="en-GB" CLASS="western" STYLE="margin-bottom: 0cm">It looks
interesting, but remember: Traduxio is a prototype, and the sand box
is only a testing space, and not the real site. So don’t expect
everything to be perfect !</P>
<P LANG="en-GB" CLASS="western" STYLE="margin-bottom: 0cm"><BR>
</P>
<P LANG="fr-FR" CLASS="western" STYLE="margin-bottom: 0cm"><SPAN LANG="en-GB">You
don’t know what to do or how to proceed&nbsp;?  Relax and try the
following&nbsp;</SPAN><FONT COLOR="#ff0000"><SPAN LANG="en-GB">.</SPAN></FONT><SPAN LANG="en-GB">
You may want to&nbsp;:</SPAN></P>
<P LANG="en-GB" CLASS="western" STYLE="margin-bottom: 0cm"><BR>
</P>
<OL>
	<LI><P LANG="fr-FR" STYLE="margin-bottom: 0cm"><SPAN LANG="en-GB"><B><a href="<?php echo $this->makeUrl("/text/deposit");?>">Deposit
	a new text</a> </B></SPAN><SPAN LANG="en-GB"></SPAN></P>
</OL>
<P LANG="fr-FR" STYLE="margin-left: 1.27cm; margin-bottom: 0cm"><SPAN LANG="en-GB">Insert
the title, the text and the metadata (genre, author, date (year only
= 4 figures))&nbsp;; then&nbsp;&quot;deposit&quot;</SPAN></P>
<P LANG="en-GB" STYLE="margin-left: 1.27cm; margin-bottom: 0cm"><BR>
</P>
<OL START=2>
	<LI><P LANG="en-GB" STYLE="margin-bottom: 0cm"><B>Consult (or Edit)
	a translation</B></P>
</OL>
<P LANG="en-GB" CLASS="western" STYLE="margin-left: 1.25cm; margin-bottom: 0cm">
Select a text from the <a href="<?php echo $this->makeUrl("/"); ?>">list</a>, then click on one of its translations.
</P>
<P LANG="fr-FR" CLASS="western" STYLE="margin-left: 1.25cm; margin-bottom: 0cm">
<SPAN LANG="en-GB">(one example <a href="<?php echo $this->makeUrl("/translation/read/id/50");?>">here</a>)</SPAN></P>
<P LANG="en-GB" CLASS="western" STYLE="margin-left: 1.25cm; margin-bottom: 0cm">
Then click on &quot;edit this translation&quot;&nbsp;</P>
<UL>
	<LI><P LANG="en-GB" STYLE="margin-bottom: 0cm">You can divide the
	source text at your convenience, by clicking on the small blue boxes
	(they have a cross (&quot;x&quot;) if you use the Firefox browser)</P>
	<LI><P LANG="en-GB" STYLE="margin-bottom: 0cm">Modify the
	translation as you wish (click on the box&nbsp;; it becomes blue,
	then feel free to write&nbsp;; don’t forget to click &quot;save&quot;
	at the bottom of the page)</P>
	<LI><P LANG="fr-FR" STYLE="margin-bottom: 0cm"><SPAN LANG="en-GB">Double
	click on a difficult word/sentence of the source text to browse the
	Translation Memory for suggestions (e.g. &quot;hommes&quot; in the
	first paragraph). </SPAN><SPAN LANG="fr-BE">The &quot;concordance&quot;
	(exact/fuzzy match results) appears as a separate window.</SPAN></P>
	<LI><P LANG="en-GB" STYLE="margin-bottom: 0cm">You can modify any
	time the parameters of your research by using the small arrows on
	the side of both the source text and the translated text 
	</P>
	<UL>
		<LI><P LANG="fr-FR" STYLE="margin-bottom: 0cm"><SPAN LANG="en-GB">Select
		the metadata type (genre, author</SPAN><SPAN LANG="en-GB">, date
		(year only = 4 figures)…), </SPAN>
		</P>
		<LI><P LANG="en-GB" STYLE="margin-bottom: 0cm">then select the
		metadata itself if you wish (Balzac, 19th century)</P>
		<LI><P LANG="en-GB" STYLE="margin-bottom: 0cm"> When you select a
		metadata, it turns into a grey box. 
		</P>
		<LI><P LANG="en-GB" STYLE="margin-bottom: 0cm">To unselect (and go
		back to the metadata menu), just click on this box.</P>
	</UL>
	<LI><P LANG="en-GB" STYLE="margin-bottom: 0cm">Come back any time to
	the main search results by clicking on the &quot;search&quot; button
	(upper right)</P>
	<LI><P LANG="en-GB" STYLE="margin-bottom: 0cm">Modify the main
	research at your convenience (change the word/sentence in the search
	box)</P>
</UL>
<P LANG="fr-FR" STYLE="margin-left: 1.27cm; margin-bottom: 0cm"><SPAN LANG="en-GB">Remark&nbsp;:
in the co</SPAN><SPAN LANG="en-GB">ncordance result, a horizontal
left-oriented Arrow appears if the translation results are reversed
(see e.g. the Genesis result at the bottom of the Balzac example&nbsp;–
the original version being in English)</SPAN></P>
<P LANG="en-GB" STYLE="margin-left: 1.27cm; margin-bottom: 0cm"><BR>
</P>
<OL START=3>
	<LI><P LANG="en-GB" STYLE="margin-bottom: 0cm"><B>Create a
	translation</B></P>
</OL>
<P LANG="en-GB" CLASS="western" STYLE="margin-left: 1.25cm; margin-bottom: 0cm">
Click on one of the texts of the <a href="<?php echo $this->makeUrl("/"); ?>">texts list</a></P>
<P LANG="en-GB" CLASS="western" STYLE="margin-left: 1.25cm; margin-bottom: 0cm">
Then click on &quot;Create a translation&quot;</P>
<P LANG="en-GB" CLASS="western" STYLE="margin-left: 1.25cm; margin-bottom: 0cm">
Insert the title and select the language of your translation&nbsp;;
then &quot;save&quot;</P>
<P LANG="fr-FR" CLASS="western" STYLE="margin-left: 1.25cm; margin-bottom: 0cm">
<SPAN LANG="en-GB">Insert metadata (author, </SPAN><SPAN LANG="en-GB">release
date (year only = 4 figures) in the upper boxes</SPAN></P>
<P LANG="en-GB" CLASS="western" STYLE="margin-left: 1.25cm; margin-bottom: 0cm">
Divide the source text using the small blue arrows</P>
<P LANG="en-GB" CLASS="western" STYLE="margin-left: 1.25cm; margin-bottom: 0cm">
Write your translation of the text on the right part of the screen</P>
<P LANG="en-GB" CLASS="western" STYLE="margin-left: 1.25cm; margin-bottom: 0cm">
Use the concordance any time you need it by double clicking on the
problematic word/sentence of the source text that you come across
-see guidelines above (2)</P>
<P LANG="en-GB" CLASS="western" STYLE="margin-left: 1.25cm; margin-bottom: 0cm">
Don’t forget to &quot;save&quot;&nbsp;– you can also choose to
&quot;cancel&quot; (bottom left)</P>
<P LANG="en-GB" CLASS="western" STYLE="margin-left: 1.25cm; margin-bottom: 0cm">
<BR>
</P>
<OL START=4>
	<LI><P LANG="fr-FR" STYLE="margin-bottom: 0cm"><SPAN LANG="en-GB"><B>Use the <a href="<?php echo $this->makeUrl("/translation/concord");?>">concordance</a> directly</B></SPAN><SPAN LANG="en-GB"></SPAN></P>
	<P LANG="en-GB" CLASS="western" STYLE="margin-left: 1.25cm; margin-bottom: 0cm">you can enter any word or group of word and check if they are present in the translation memory</P>
	</LI>
</OL>
<BR>
</P>
<OL START=5>
	<LI><P LANG="fr-FR" STYLE="margin-bottom: 0cm"><SPAN LANG="en-GB"><B>Send
	us your <a href="mailto:traduxio.feedback@gmail.com">feedback</a></B></SPAN><SPAN LANG="en-GB"></SPAN></P>
</OL>
<P LANG="en-GB" CLASS="western" STYLE="margin-left: 1.25cm; margin-bottom: 0cm">
… or even become one of our beta-testers&nbsp;! Thanks</p>
</div>
</div>
<!--</div>-->
</div>
