sudo: false

services: couchdb

language:
  - ruby
  - python

rvm: 2.3.1

cache:
  directories:
    #We cache gems for poltergeist and .local for couchapp,
    #the longest tools to install
    - ~/.rvm/gems
    - ~/.local

install:
  - pip install --user couchapp
  - gem install poltergeist rspec

script: ./test.sh
