<?php 
$this->layout()->setLayout('empty');?>
<?php if($this->canTag): ?><div class="add-tag" title="<?php echo __("Add a new tag");?>">+</div><?php endif; ?>
<?php if(!empty($this->tags)): ?>
<?php foreach($this->tags as $genre=>$tags): ?>
<div class="tag-group" id="group-<?php echo $genre?>">
<span class="genre" id="<?php echo $genre?>"><?php echo __($this->genres[$genre]); ?></span>
<?php foreach($tags as $key=>$tag):?>

<span class="tag-item" title="<?php echo __(strtolower($tag['genre_name'])); ?>"><span class="tag-text"><?php echo $tag['comment']; ?></span>
<?php if(is_array($tag)&&(!is_null($this->userid))&&($tag['user']==$this->userid)):?>
    
    <span><a class="delete" id="<?php echo $genre.'-'.$tag['id']?>" onmouseover="this.style.cursor= 'pointer'"> X </a></span>
<?php endif; ?>
</span>
<?php endforeach; ?>
</div>
<?php endforeach; ?>
<?php endif; ?>


