
<?php
$this->layout()->setLayout('jsonlayout');
$this->work['language']=__($this->work['language']);
$translations = array();
/*if(!empty($this->work['Sentences'])){
    foreach($this->work['Sentences'] as $key=>$sentence){
        $this->work['Sentences'][$key]['content'] = $this->nlBr($sentence['content']);
    }
}*/
if(!empty($this->work['Interpretations'])){
    foreach($this->work['Interpretations'] as $key=>$trl){
   /*     foreach($trl['blocks'] as $ind=>$block){
            $this->work['Interpretations'][$key]['blocks'][$ind]['translation'] = $this->nlBr($block['translation']);
        }
     */   $this->work['Interpretations'][$key]['work']['language']=__($trl['work']['language']);
    }
}

$data=array('work'=>$this->work,'tags'=>$this->tagbody,'tagform'=>$this->tagform,'translation'=>$this->trWork);

Tdxio_Log::info(Zend_Json::encode($data),'jsondata');

echo Zend_Json::encode($data); 
