<?php
// application/views/scripts/text/extend.phtml
/***
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; version 2 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 **/

?><?php echo $this->headScript()->appendFile($this->makeUrl('/js/autogrow.js')); ?>
<?php $dir = (($this->text['rtl']==1)?'dir="rtl"':''); ?>

<div class="central-home">
<div class = "work-container hundred" <?php echo $dir ?>>
<div class="title"><?php echo $this->escape($this->text['title']); ?></div>
<div class="language"><?php echo __($this->text['language']); ?></div>
<br/><span class="label"><?php echo __('Last segment of the text') ?></span>

<div class="text" lang="<?php echo $this->text['language'] ?>">
<span class="segment"></span><?php echo $this->lasttext; ?>
</div>
<div class="form">
<?php echo $this->form ?>
</div></div></div>
<?php $this->page_title=__('PAGETITLE_Continue text insertion').':'.$this->escape($this->text['title']); ?>
