<?php $this->headScript()->appendFile($this->makeUrl('/js/close-ul.js')); ?>

<table class="home">
<tr><td class="logo">
<div class="logo"><img src="<?php echo $this->makeUrl('/images/traduxio_home_logo.jpg'); ?>">
<div class="citation"><?php echo __('HOMEPAGE PHRASE') ?><span class="author">Eugenio Coseriu</span></div>
<div class="site-title"><?php echo __('Translating cultural texts') ?></div>
</div>
</td>
<td class="lang-list">

          
<ul>
<?php
foreach ($this->entries as $lang=>$authors) { ?>
    <li class='language'><?php echo $lang;?>
        <ul class='authors'>
<?php   foreach ($authors as $author=>$texts) { ?>
            <li class='author closed'><?php echo $author; ?>
            <ul class='texts'>
<?php       foreach ($texts as $text) { ?>
                <li class='text'><a href="<?php echo $this->url(
                    array('controller'=>'work','action'=>'read','id'=>$text['id'])) ?>">
                    <?php if($text['title']==''){echo '<i>'.__('No Title').'</i>';}else{echo $text['title'];} ?></a>
                    <?php if($text['count']>0):?><span class="trCount"> <?php echo __("(%1\$s Translations)",$text['count']);?></span><? endif; ?>
                </li>
<?php       } ?>
            </ul></li>
<?php   } ?>
        </ul></li>
<?php } ?>
</ul>
          
<dl>
    <!-- Loop through the entries that were provided to us by the controller -->
    <?php foreach ($this->entries as $entry): ?>
    <dt><a href="<?php echo $this->url(
            array('controller'=>'work','action'=>'read','id'=>$entry['id'])) ?>">
                         <?php echo $this->escape($entry->title) ?></a></dt>
  <?php endforeach ?>
</dl>
</td>

<td class="news hundred">
    <div class="news-paragraph"><div class="news-title"><?php echo __('Latest News');?></div>
    <?php foreach($this->news as $ageInSec=>$list): ?>
        <?php foreach($list as $key=> $item): ?>
            <ul><li>
            <?php echo $item['phrase']; ?>
            <?php  /*if($item['type']=='orig'){
                        $title = '<a href="'.$this->makeUrl('/work/read/id/'.$item['id']).'">'.$item['title'].'</a>';
                        $user = 'TEMPUSER';
                        if($item['NM']=='NEW'){
                            echo __("\"%1\$s\", new text added by %2\$s",$title,$user);
                        }
                        elseif($item['NM']=='MOD'){
                            echo __("\"%1\$s\", text modified by %2\$s",$title,$user);
                        }
                    }elseif($item['type']=='tra'){
                        $title = '<a href="'.$this->makeUrl('/translation/read/id/'.$item['id']).'">'.$item['title'].'</a>';
                        $origtitle = '<a href="'.$this->makeUrl('/work/read/id/'.$item['orig_id']).'">'.$item['orig_title'].'</a>';
                        $user = 'TEMPUSER';
                        if($item['NM']=='NEW'){
                            echo __("\"%1\$s\", added translation of %2\$s by %3\$s",$title,$origtitle,$user);
                        }
                        elseif($item['NM']=='MOD'){
                            echo __("\"%1\$s\", translation of %2\$s, modified by %3\$s",$title,$origtitle,$user);
                        }
                    }elseif($item['type']=='tag'){
                        $tag = '<a href="'.$this->makeUrl('/work/read/id/'.$item['taggable']).'">'.$item['comment'].'</a>';
                        $taggedText = '<a href="'.$this->makeUrl('/work/read/id/'.$item['taggable']).'">'.$item['commment'].'</a>';
                        $user = 'TEMPUSER';
                        if($item['NM']=='NEW'){
                            echo __("\"%1\$s\", added (%2\$s) tag to text %3\$s by %4\$s",$tag,$item['genre'],$taggedText,$user);
                        }
                        elseif($item['NM']=='MOD'){
                            echo __("\"%1\$s\" (%2\$s) tag on text %3\$s modified by %4\$s",$tag,$item['genre'],$taggedText,$user);
                        }
                    }*/ 
            ?>
        
            <?php $age=$item['age']; ?>
            <span class="age">
            <?php if($age < 60){$age = round($age);$units =__('seconds');}
            elseif($age < 3600){$age = round($age/60); $units = __('minutes');}
            elseif($age < 86400){$age = round($age/3600); $units = __('hours');}
            elseif($age < 2592000){$age = round($age/86400); $units = __('days');}
            echo __("%1\$s %2\$s ago",$age,$units);
            ?>
            </span>    
            </li></ul>
        <?php endforeach; ?>
    <?php endforeach; ?>
    </div>
</td>
</tr>
</table>

<?php $this->page_title=__('Homepage'); ?>
