<?php $this->headScript()->appendFile($this->makeUrl('/js/close-ul.js')); ?>
<?php 
    function plural($sing, $plur, $number){
        if($number==0 or $number == 1)
            return __($sing);
        else
            return __($plur);
    }
?>
<table class="home">
<tr><td class="logo">
<div class="logo"><img src="<?php echo $this->makeUrl('/images/traduxio_home_logo.jpg'); ?>" alt="TraduXio Home Logo" />
<div class="citation"><?php echo __('HOMEPAGE PHRASE') ?><span class="author">Eugenio Coseriu</span></div>
<!--<div class="site-title"><?php //echo __('Translating cultural texts') ?></div>-->
</div>
</td>
<td class="lang-list">

<ul>
<?php
foreach ($this->entries as $lang=>$authors) { ?>
    <li class='language'><?php echo $lang;?>
        <ul class='authors'>
<?php   foreach ($authors as $author=>$texts) { ?>
            <li class='author closed'><?php echo $author; ?>
            <ul class='texts'>
<?php       foreach ($texts as $text) { ?>
                <li class='text'><span <?php if($text['rtl']==1){echo 'class="fl-left" dir="rtl"'; $nbsp = '&nbsp;';}else{$nbsp='';} ?>><a href="<?php echo $this->url(
                    array('controller'=>'work','action'=>'newread','id'=>$text['id'])) ?>">
                    <?php if($text['title']==''){echo '<i>'.__('No Title').'</i>';}else{echo $text['title'];} ?></a></span><?php echo $nbsp; ?>
                    <?php if($text['count']>0):?><span class="trCount"> <?php echo ($text['count']>1)?__("(%1\$s Translations)",$text['count']):__("(%1\$s Translation)",$text['count']);?></span><? endif; ?>
                </li>
<?php       } ?>
            </ul></li>
<?php   } ?>
        </ul></li>
<?php } ?>
</ul>
</td>
<td class="lang-list">
<br>
<a id="insert-text" href="<?php echo $this->url(array('controller'=>'work','action'=>'deposit')) ?>"><?php echo __("Deposit a new text");?></a>
</td class="lang-list">
<td class="news hundred">
    <div class="news-paragraph"><div class="news-title"><?php echo __("New translations in %1\$s",__($this->newsLang));?></div>
    <?php if(!empty($this->news)):?><ul class = "new-translation"><?php 
        foreach($this->news as $key=> $item): ?>
            <li><a href = "<?php echo $this->url(
            array('controller'=>'work','action'=>'newread','id'=>$item['tr_id'])) ?>"
            <?php if($item['rtl']==1) echo 'dir="rtl"'?> >
            <?php echo $item['orig_title']; ?></a>
            </li>
        <?php endforeach; ?></ul><?php endif;?>
    </div>
</td>
</tr>
</table>

<?php $this->page_title=__('PAGETITLE_Homepage'); ?>
