<?php
// application/views/scripts/work/manage.phtml
/***
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; version 2 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 **/
?>
<?php $this->headScript()->appendFile($this->makeUrl('/js/hide.js')); ?>
<?php $this->page_title= __("Manage text's privileges").$this->escape($this->work['title']); ?>

<div class="central-home">
<span class="manage-link"><a href="<?php echo $this->makeUrl('/work/newread/id/'.$this->work_id); ?>"><?php echo __('Back to the text'); ?></a></span>
<span class="manage-link"><a href="<?php echo $this->makeUrl('/work/switch/id/'.$this->work_id); ?>"><?php echo __($this->link); ?></a></span>

<?php if($this->visibility=='public' or $this->visibility=='private'): ?>
<div class="title"><?php echo __('Standard Privileges') ?></div>
<?php echo $this->stdform; ?>
<?php endif; ?>

<?php if($this->visibility=='custom'): ?>
<div class="title"><?php echo __('Custom Privileges') ?></div>
<div id="custom">
<?php if($this->remform): ?>
<div id="rem-privilege" class="privilege-form" title="<?php echo __('Select and click on Remove Privilege to delete a permission') ?>"> 
<div class="title"><?php echo __('Remove an existing permission') ?> </div>

<?php echo $this->remform; ?></div>
<?php else: ?> <div id="rem-privilege" class="privilege-form"> <div class="title"> <?php echo __('NO EXISTING PRIVILEGES') ?> </div></div>
<?php endif; ?>
<div id="add-privilege" class="privilege-form">
<div class="title"><?php echo __('Add a new permission') ?></div>
<?php echo $this->addform; ?>
</div>
</div>
<?php endif; ?>
</div>
<?php $this->page_title=__('PAGETITLE_Continue text insertion').':'.$this->escape($this->text['title']); ?>


