<div id="margin">
<div id="page-title">
<?php echo __('My translations'); ?>
</div>
<ul>
<?php if(empty($this->myEntries)) {echo __("You have not inserted any text's translations");} ?>
<?php foreach ($this->myEntries as $srcLang=>$trlLang):?>
<?php foreach ($trlLang as $lang=>$texts):?>
    <li class='srcLang'> <?php echo __($srcLang);?> <img src="<?php echo $this->makeUrl('/images/arrow-right.png'); ?>"> <?php echo __($lang);?></li>
    <ul class='trl'>
<?php foreach ($texts as $text): ?>
    <li class='text my'>
    <a href="<?php echo $this->url(array('controller'=>'translation','action'=>'read','id'=>$text['id'])) ?>">
        <?php if($text['title']==''){echo '<i>'.__('No Title').'</i>';}else{echo $text['title'];} ?>
    </a></li>
<?php endforeach; ?>
</ul>
<br>
<?php endforeach; ?>
<?php endforeach; ?>

</ul>
</div>
<?php $this->page_title = __("PAGETITLE_My translations");?>
