<?php $this->headScript()->appendFile($this->makeUrl('/js/page.js')); ?>
<?php $this->headScript()->appendFile($this->makeUrl('/js/jqueryslidemenu.js')); ?>
<?php $this->headScript()->appendFile($this->makeUrl('/js/actions.js')); ?>
<?php $this->headScript()->appendFile($this->makeUrl('/js/tag.js')); ?>
<?php $this->headScript()->appendFile($this->makeUrl('/js/lib/jquery.scrollTo-min.js')); ?>
<?php $this->headScript()->appendFile($this->makeUrl('/js/lib/jquery.jeditable.js')); ?>
<?php $this->headScript()->appendFile($this->makeUrl('/js/lib/selectedText.min.js')); ?>
<?php $this->headScript()->appendFile($this->makeUrl('/js/lib/jquery.jqprint.js')); ?>
<?php $this->headScript()->appendFile($this->makeUrl('/js/nl2br.js')); ?>
<?php $this->layout()->setLayout('layout-black');?>

<?php 
$href= 'href="'.$this->url(array('controller'=>'work','action'=>'translate','id'=>$this->work['id'])).'"';
$href_extend= 'href="'.$this->url(array('controller'=>'work','action'=>'extend','id'=>$this->work['id'])).'"';
$href_edit = 'href="'.$this->url(array('controller'=>'work','action'=>'edit','id'=>$this->work['id'])).'"';
$explainNA=($this->isMember)?__("You're not allowed to do this. Ask permissions to the text's owner"):__("You're not allowed to do this. Please login");
$NRattrs = 'class="idle" title="'.$explainNA.'"';
$HTmessage = __("You can't delete this text because it has some translations. Delete its translations first.");
$askConfirm = __("WARNING! Deletion is a definitive choice! Are you SURE you want to delete this text?");
$dir = (($this->work['rtl']==1)?'dir="rtl"':''); 
?>
<div id="hint"></div>
<div class="show-note"><span class="closeimg" title="<?php echo __("Close");?>"></span><span class="text"></span><a href="#" class="delete" class="hidden" title="<?php echo __("Delete")?>">X</a></div>
<div id="test"></div><div id="myslidemenu" class="jqueryslidemenu clear">
    <ul>
        <li><a href="#"><div id='options'></div></a>
            <ul>
				<li id="showtags"><a href="#"><?php echo __('Show Tags'); ?></a></li>
                <li id="note" <?php echo ($this->canTag?'':$NRattrs); ?>><a href="#"><?php echo __('Tag a sentence'); ?></a></li>
                <li id="translate" <?php echo ($this->canTranslate?'':$NRattrs); ?>><a <?php echo $href; ?>><?php echo __('Create a translation'); ?></a></li>
                <li id="extend" <?php echo ($this->canEdit?'':$NRattrs); ?>><a <?php echo $href_extend;?>><?php echo __('Continue text insertion'); ?></a></li>                                
                <li id="edit-meta" <?php echo ($this->canEdit?'':$NRattrs); ?>><a href="#"><?php echo __("Edit work's info"); ?></a></li>                                
                <li id="edit" <?php echo $NRattrs;?>><a href="#"><?php echo __("Edit the translation"); ?></a></li>                                
                <li><a href="#"><?php echo __("Manage privileges"); ?></a>
				<ul><li id="manage-orig" <?php echo ($this->canManage?'':$NRattrs); ?> ><a href="<?php echo $this->url(array('controller'=>'work','action'=>'manage','id'=>$this->work['id'])) ?>"><?php echo __("Manage text's privileges"); ?></a></li>
					<li id="manage" class="idle"><a href="#"><?php echo __("Manage translation's privileges"); ?></a></li>
				</ul></li>
                <li><a href="#"><?php echo __("Delete"); ?></a><ul>
                <?php if($this->canDelete): 
                    if($this->hasTranslations==false):                         
                        $href= 'href="'.$this->url(array('controller'=>'work','action'=>'delete','id'=>$this->work['id'])).'" onClick="'."return confirm('".$askConfirm."')".'"' ;$msg=__("Warning!This is a definitive choice!");
                    else: $href = 'href=""'; $msg = 'class="idle" title="'.$HTmessage.'" onClick="alert(\''.addslashes($HTmessage).'\');"';
				endif;?>
				<?else: $href = 'href=""';$msg = 'class="idle" title="'.$explainNA.'" onClick="alert(\''.addslashes($explainNA).'\');"';?>					
				<?endif; ?>
				<li id="delete-orig" <?php echo $msg; ?>><a <?php echo $href; ?> ><?php echo __("Delete this text"); ?></a></li>                
                <li id="delete" class="idle" title="<?php echo __("Warning!This is a definitive choice!");?>"><a href="#"><?php echo __("Delete this translation"); ?></a></li>                
                </ul></li>
                <li><a href="#"><?php echo __("History"); ?></a><ul>
					<li id="history-orig"><a href="<?php echo $this->makeUrl('/work/history/id/'.$this->work['id']); ?>" ><?php echo __("Original work's history"); ?></a></li>
					<li id="history" class="idle"><a href="#" ><?php echo __("Translation's history"); ?></a></li>
				</ul></li>
            </ul>
        </li>
    </ul>
</div>
<div id="menu" title="<?php echo __("Show/Hide icons");?>"><?php echo __("Icons"); ?></div>
<div class="background">
<div id="new-translation"><div id="form-title"><?php echo __("Create a translation");?></div></div>
<div id="insert-sentence-tag"></div>

<!-------------------------------!-->
<div id="tests"></div>
<div id="show-icons" class="hidden">
	<div class="icons" id="orig-icons">        
		<?php if($this->canDelete): 
			if($this->hasTranslations==false): 
			$href= 'href="'.$this->url(array('controller'=>'work','action'=>'delete','id'=>$this->work['id'])).'" onClick="'."return confirm('".$askConfirm."')".'"' ;
			else: $href = 'href="" class="idle" title="'.$HTmessage.'" onClick="alert(\''.addslashes($HTmessage).'\');"'; 
			endif;?>
		<a <?php echo $href; ?> ><div><span class="delbtn" title="<?php echo __("Delete this text"); ?>"></span><span class="icon-label"><?php echo __("Delete");?></span></div></a>
		<?endif; ?>
		<div class="separate"></div>
		<div><span class="printbtn" title="<?php echo __("Print the original text"); ?>"></span><span class="icon-label"><?php echo __("Print");?></span></div>
		<div class="separate"></div>
		<a href="<?php echo $this->makeUrl('/work/history/id/'.$this->work['id']); ?>" ><div><span class="history" title="<?php echo __("History of modifications"); ?>"></span><span class="icon-label"><?php echo __("Log");?></span></div></a>
		<?php if($this->canManage):?><a href="<?php echo $this->url(array('controller'=>'work','action'=>'manage','id'=>$this->work['id'])) ?>"><div><span class="manage" title="<?php echo __("Manage privileges"); ?>"></span><span class="icon-label"><?php echo __("Manage");?></span></div></a><?php endif; ?>
		<div class="separate"></div>	
		<div <?php if(!$this->canTag){echo 'class="idle"';}?>><span id="notebtn" title="<?php echo __("Tag a sentence"); ?>"></span><span class="icon-label"><?php echo __("Notes");?></span></div>
		<div><span id="show-tag" title="<?php echo __("Show Tags"); ?>"></span><span class="icon-label"><?php echo __("Tags");?></span></div>
		<div class="separate"></div>
		<div <?php if(!$this->canEdit){echo 'class="idle"';}?>><span class="extbtn" title="<?php echo __("Continue text insertion"); ?>"></span><span class="icon-label"><?php echo __("Add");?></span></div>
		<div <?php if(!$this->canEdit){echo 'class="idle"';}?>><span id="editmeta" title="<?php echo __("Edit the text"); ?>"></span><span class="icon-label"><?php echo __("Edit");?></span></div>
	</div>
	<div class="icons" id="tr-icons">
		<div class="idle"><span class="delbtn" title="<?php echo __("Delete this translation"); ?>"></span><span class="icon-label"><?php echo __("Delete");?></span></div>
		<div class="separate"></div>		
		<div><span class="printbtn" title="<?php echo __("Print this translation"); ?>"></span><span class="icon-label"><?php echo __("Print");?></span></div>
		<div class="separate"></div>
		<a href="<?php echo $this->makeUrl('/work/history/id/'.$this->work['id']); ?>" ><div class="idle"><span class="history" title="<?php echo __("History of modifications"); ?>"></span><span class="icon-label"><?php echo __("Log");?></span></div></a>
		<a href="<?php echo $this->url(array('controller'=>'work','action'=>'manage','id'=>$this->work['id'])) ?>"><div class="idle"><span class="manage" title="<?php echo __("Manage privileges"); ?>"></span><span class="icon-label"><?php echo __("Manage");?></span></div></a>
		<div class="separate"></div>
		<div><span id="show-tag" title="<?php echo __("Show Tags"); ?>"></span><span class="icon-label"><?php echo __("Tags");?></span></div>
		<div class="separate"></div>
		<div class="idle"><span id="editbtn" title="<?php echo __("Edit translation"); ?>"></span><span class="icon-label"><?php echo __("Edit");?></span></div>
	</div>
</div>
	
<div class="tag-line clear">
    <div class="show-tag-area" id="orig-tag" dir=<?php echo $dir; ?>>
		 <?php echo $this->tagbody; ?>
    </div>
    <div class="show-tag-area" id="tr-tag">		
    </div>
</div> 
<div id="book"> 
<div class="page-container" id="left-page" <?php echo $dir ?>>

    <div class="clear">
        <div class="TLcorner"></div>
        <div class="Tborder center"></div>
        <div class="TRcorner"></div>
    </div>
    
    <div class="clear">
        <div class="Lborder middle" id="prev-page" >
            <a href="#"><img class="turn-page" src="<?php echo $this->makeUrl('/images/previous.png'); ?>"/></a>
        </div>
        <div class="text-container center" id="work">
        <div class="work-title red"> <?php $author = ($this->work['author']=='')?__('Anonymous'):$this->work['author'];?>
            <span class="author" id="orig-author"><?php echo $author ?></span>
            ,
            <span class="title" id="orig-title"><?php echo $this->work['title']; ?></span>
        </div> 
        
       <!-- <div class="language TBspaced red"><?php //echo __($this->work['language']); ?></div> !-->
        <div class="text show">
            <?php foreach ($this->work['Sentences'] as $segnum=>$sentence) : ?>
                <?php $segment_id="text".$this->work['id']."-segment".$segnum; ?>
               <span class="segment" id="<?php echo $segment_id; ?>"><?php //echo $this->nlBr($sentence['content']); ?></span>
                <?php //if(!empty($this->work['SentencesTags'][$segnum])): ?>
                <?php //foreach($this->work['SentencesTags'][$segnum] as $key=>$stag): ?>
                <!--<span class="note-symbol"><?php //echo $key; ?></span>!-->
                <?php //endforeach; ?>
                <?php //endif; ?>
            <?php endforeach; ?>
        </div>            
        </div>
        <div class="Rborder middle"></div>
    </div>
    
    <div class="clear">
        <div class="BLcorner"></div>
        <div class="Bborder center"><div class = "creator"> <?php echo (__('Text inserted by')).' ';  echo ($this->work['creator']); ?> </div></div>
        <div class="BRcorner"></div>
    </div>
    
</div>
<div class="page-container" id="right-page">
<?php //if(empty($this->work['Interpretations'])): ?>
<?php if(!$this->hasTranslations): ?>
<?php $ongletClass = "hidden"; $borderClass = "visible";?>    
<?php else: $ongletClass = "visible"; $borderClass = "hidden";?>
<?php endif; ?>
<div class="clear <?php echo $borderClass; ?>" id="top-border">
        <div class="TLcorner"></div>
        <div class="Tborder center"></div>
        <div class="TRcorner"></div>
</div>
<div class="clear <?php echo $ongletClass; ?>" id="plus" >
<ul class="onglets">
<?php foreach($this->work['Interpretations'] as $traId=>$trWork): ?>

    <li class="onglet" id="onglet-<?php echo $traId;?>">
        <span title="<?php echo __($trWork['work']['language']) ?>">
            <a href="#<?php echo 'tr'.$traId; ?>"><?php echo $trWork['work']['translator'];?></a>
        </span>
    </li>    
<?php endforeach; ?>
<span id='more'>+</span>
</ul>    
</div>
    
    <div class="clear">
        <div class="Lborder middle"></div>
        <div class="text-container center" id="translation">
        	
        <div class="work-title red"> 
            <span class="author" id="tr-author"></span>
            <span class="title" id="tr-title"></span>
        </div>
        
        <div class="text show">
        <?php if(!$this->trId):?>
        <span id="create"><?php echo __('Create a translation'); ?></span>
        <?php endif; ?>
        </div>            
        </div>
        <div class="Rborder middle" id="next-page" >
            <a href="#"><img class = "turn-page" src="<?php echo $this->makeUrl('/images/next.png'); ?>" /></a>
        </div>
    </div>
    
    <div class="clear">
        <div class="BLcorner"></div>
        <div class="Bborder center"></div>
        <div class="BRcorner"></div>
    </div>
    
</div>
</div>
<span class="comments">
<span id="showtagstext"><?php echo __("Show tags");?></span>
<span id="hidetagstext"><?php echo __("Hide tags");?></span>
<span id="clicktoedit"><?php echo __("Click to edit");?></span>
<span id="want2delete"><?php echo $askConfirm;?></span>
<span id="missingpriv"><?php echo $explainNA;?></span>
<span id="notehint"><?php echo __("Click on a sentence to insert a tag/note for it");?></span>
</span>
</div>

<?php $this->page_title = __("PAGETITLE_Read text").': '.$this->escape($this->work['title']); ?>
