<?php $this->headScript()->appendFile($this->makeUrl('/js/page.js')); ?>
<?php $this->headScript()->appendFile($this->makeUrl('/js/jqueryslidemenu.js')); ?>
<?php $this->headScript()->appendFile($this->makeUrl('/js/actions.js')); ?>
<?php $this->headScript()->appendFile($this->makeUrl('/js/tag.js')); ?>
<?php $this->headScript()->appendFile($this->makeUrl('/js/lib/jquery.scrollTo-min.js')); ?>
<?php $this->headScript()->appendFile($this->makeUrl('/js/lib/jquery.jeditable.js')); ?>
<?php $this->headScript()->appendFile($this->makeUrl('/js/lib/selectedText.min.js')); ?>
<?php $this->headScript()->appendFile($this->makeUrl('/js/nl2br.js')); ?>
<?php $this->layout()->setLayout('layout-black');?>

<?php 
$href= 'href="'.$this->url(array('controller'=>'work','action'=>'translate','id'=>$this->work['id'])).'"';
$href_extend= 'href="'.$this->url(array('controller'=>'work','action'=>'extend','id'=>$this->work['id'])).'"';
$href_edit = 'href="'.$this->url(array('controller'=>'work','action'=>'edit','id'=>$this->work['id'])).'"';
$explainNA=($this->isMember)?__("You're not allowed to do this. Ask permissions to the text's owner"):__("You're not allowed to do this. Please login");
$NRattrs = 'class="idle" title="'.$explainNA.'"';
$HTmessage = __("You can't delete this text because it has some translations. Delete its translations first.");
$askConfirm = __("WARNING! Deletion is a definitive choice! Are you SURE you want to delete this text?");
$dir = (($this->work['rtl']==1)?'dir="rtl"':''); 
?>
<div id="test"></div><div id="myslidemenu" class="jqueryslidemenu clear">
    <ul>
        <li><a href="#"><div id='options'></div></a>
            <ul>
                <li id="translate"><a <?php echo $href.' '.($this->showTranslate?'':$NRattrs); ?>><?php echo __('Create a translation'); ?></a></li>
                <li id="extend"><a <?php echo $href_extend.' '.($this->showEdit?'':$NRattrs); ?>><?php echo __('Continue text insertion'); ?></a></li>
                <?php if($this->canManage): ?>
                <li id="manage"><a href="<?php echo $this->url(array('controller'=>'work','action'=>'manage','id'=>$this->work['id'])) ?>"><?php echo __("Manage text's privileges"); ?></a></li>
                <?php endif; ?>
                <?php if($this->canDelete): 
                    if($this->hasTranslations==false): 
                        
                        $href= 'href="'.$this->url(array('controller'=>'work','action'=>'delete','id'=>$this->work['id'])).'" onClick="'."return confirm('".$askConfirm."')".'"' ;
                    else: $href = 'href="" class="idle" title="'.$HTmessage.'" onClick="alert(\''.addslashes($HTmessage).'\');"'; 
                    endif;?>
                    <li id="delete"><a <?php echo $href; ?> ><?php echo __("Delete this text"); ?></a></li>
                <?endif; ?>
                <li id="history"><a href="<?php echo $this->makeUrl('/work/history/id/'.$this->work['id']); ?>" ><?php echo __("History of modifications"); ?></a></li>
            </ul>
        </li>
    </ul>
</div>
<div class="background">
<div id="new-translation"><div id="form-title"><?php echo __("Create a translation");?></div></div>

<!-------------------------------!-->
<div id="tests"></div>
<div id="show-icons">
	<div class="icons" id="orig-icons">        
		<?php if($this->canDelete): 
			if($this->hasTranslations==false): 
			$href= 'href="'.$this->url(array('controller'=>'work','action'=>'delete','id'=>$this->work['id'])).'" onClick="'."return confirm('".$askConfirm."')".'"' ;
			else: $href = 'href="" class="idle" title="'.$HTmessage.'" onClick="alert(\''.addslashes($HTmessage).'\');"'; 
			endif;?>
		<a <?php echo $href; ?> ><div class="delbtn" title="<?php echo __("Delete this text"); ?>"></div></a>
		<?endif; ?>
		<div class="separate"></div>
		<div class="printbtn" title="<?php echo __("Print the original text"); ?>"></div>
		<div class="separate"></div>
		<a href="<?php echo $this->makeUrl('/work/history/id/'.$this->work['id']); ?>" ><div class="history" title="<?php echo __("History of modifications"); ?>"></div></a>
		<a href="<?php echo $this->url(array('controller'=>'work','action'=>'manage','id'=>$this->work['id'])) ?>"><div class="manage" title="<?php echo __("Manage privileges"); ?>"></div></a>
		<div class="separate"></div>	
		<div id="show-tag" title="<?php echo __("Show TAGS"); ?>"></div>
		<div class="extbtn" title="<?php echo __("Extend the text"); ?>"></div>
		<div id="editmeta" title="<?php echo __("Edit the text"); ?>"></div>		
	</div>
	<div class="icons" id="tr-icons">
		<div class="delbtn" title="<?php echo __("Delete this translation"); ?>"></div>		
		<div class="separate"></div>		
		<div class="printbtn" title="<?php echo __("Print this translation"); ?>"></div>
		<div class="separate"></div>
		<div class="history" title="<?php echo __("History of modifications"); ?>"></div>
		<div class="manage" title="<?php echo __("Manage privileges"); ?>"></div>
		<div class="separate"></div>
		<div id="show-tag" title="<?php echo __("Show TAGS"); ?>"></div>
		<div id="editbtn" title="<?php echo __("Edit translation"); ?>"></div>
	</div>
</div>
	
<div class="tag-line clear">
    <div class="show-tag-area" id="orig-tag">
		 <?php echo $this->tagbody; ?>
    </div>
    <div class="show-tag-area" id="tr-tag">		
    </div>
</div> 
<div id="book"> 
<div class="page-container" id="left-page" <?php echo $dir ?>>

    <div class="clear">
        <div class="TLcorner"></div>
        <div class="Tborder center"></div>
        <div class="TRcorner"></div>
    </div>
    
    <div class="clear">
        <div class="Lborder middle" id="prev-page" >
            <a href="#"><img class="turn-page" src="<?php echo $this->makeUrl('/images/previous.png'); ?>"/></a>
        </div>
        <div class="text-container center" id="work">
        <div class="work-title red"> <?php $author = ($this->work['author']=='')?__('Anonymous'):$this->work['author'];?>
            <span class="author" id="orig-author"><?php echo $author ?></span>
            ,
            <span class="title" id="orig-title"><?php echo $this->work['title']; ?></span>
        </div> 
        
       <!-- <div class="language TBspaced red"><?php //echo __($this->work['language']); ?></div> !-->
        <div class="text show">
            <?php foreach ($this->work['Sentences'] as $segnum=>$sentence) : ?>
                <?php $segment_id="text".$this->work['id']."-segment".$segnum; ?>
                <span class="segment" id="<?php echo $segment_id; ?>"><?php //echo $this->nlBr($sentence['content']); ?></span>
            <?php endforeach; ?>
        </div>            
        </div>
        <div class="Rborder middle"></div>
    </div>
    
    <div class="clear">
        <div class="BLcorner"></div>
        <div class="Bborder center"><div class = "creator"> <?php echo (__('Text inserted by')).' ';  echo ($this->work['creator']); ?> </div></div>
        <div class="BRcorner"></div>
    </div>
    
</div>
<div class="page-container" id="right-page">
<?php //if(empty($this->work['Interpretations'])): ?>
<?php if(!$this->hasTranslations): ?>
    <div class="clear">
        <div class="TLcorner"></div>
        <div class="Tborder center"></div>
        <div class="TRcorner"></div>
    </div>
<?php else: ?>
<div class="clear" id="plus" >
<ul class="onglets">
<?php foreach($this->work['Interpretations'] as $traId=>$trWork): ?>

    <li class="onglet" id="onglet-<?php echo $traId;?>">
        <span title="<?php echo __($trWork['work']['language']) ?>">
            <a href="#<?php echo 'tr'.$traId; ?>"><?php echo $trWork['work']['creator'];?></a>
        </span>
    </li>    
<?php endforeach; ?>
<span id='more'>+</span>
</ul>    
</div>
<?php endif; ?>
    
    <div class="clear">
        <div class="Lborder middle"></div>
        <div class="text-container center" id="translation">
        	
        <div class="work-title red"> 
            <span class="author" id="tr-author"></span>
            ,
            <span class="title" id="tr-title"></span>
        </div>
        
        <div class="text show">
        <?php if(!$this->trId):?>
        <span id="create"><?php echo __('Create a translation'); ?></span>
        <?php endif; ?>
        </div>            
        </div>
        <div class="Rborder middle" id="next-page" >
            <a href="#"><img class = "turn-page" src="<?php echo $this->makeUrl('/images/next.png'); ?>" /></a>
        </div>
    </div>
    
    <div class="clear">
        <div class="BLcorner"></div>
        <div class="Bborder center"></div>
        <div class="BRcorner"></div>
    </div>
    
</div>
</div>
<span class="comments">
<span id="clicktoedit"><?php echo __("Click to edit");?></span>
<span id=""><?php echo __("");?></span>
<span id=""><?php echo __("");?></span>
</span>
</div>

<?php $this->page_title = __("PAGETITLE_Read text").': '.$this->escape($this->work['title']); ?>
