<?php $this->headScript()->appendFile($this->makeUrl('/js/myprint.js')); ?>
<?php $this->headLink()->appendStylesheet($this->makeUrl('/css/oldpage.css')) ?>
<?php $this->layout()->setLayout('nolayout');?>
<link rel="stylesheet" type="text/css" media="print" href="<?php echo $this->makeUrl('/css/print.css'); ?>" />

<?php $dir = (($this->work['rtl']==1)?'dir="rtl"':''); ?>

<div id="page-container">

<div class="reductor print">
<div class = "Tborder"><div class = "TLcorner"></div><div class = "TRcorner"></div></div>
        <div class="Lborder hundred"><div class="Rborder hundred">
            <div class = "work-container hundred" <?php echo $dir ?>>
                <div class = "title" id="work-title"><?php $author = ($this->work['author']=='')?__('Anonymous'):$this->work['author'];?>
                <span class="author"><?php echo $author.', ' ?></span>
                <a href="<?php echo $this->makeUrl('/work/newread/id/'.$this->work['id']);?>"><span><?php echo $this->work['title']; ?></span></a>
                <img id="printbtn" src="<?php echo $this->makeUrl('/images/print.png');?>" title="<?php echo __('Print'); ?>">
                </div>
                
                <div class="language">
                <?php echo __($this->work['language']); ?></div>
                <div class = "text"> 
                    <?php foreach ($this->work['Sentences'] as $segnum=>$sentence) : ?>
                        <?php $segment_id="text".$this->work['id']."-segment".$segnum; ?>
                        <span class="segment" id="<?php echo $segment_id; ?>"><?php echo $this->nlBr($sentence['content']); ?></span>
                    <?php endforeach; ?>
                </div>
                <div class = "creator"> </div>
            </div>  
        </div></div>
    
<div class = "Bborder"><div class = "BLcorner"></div><div class = "BRcorner"></div></div>
</div>
</div>
<?php $this->page_title = __("PAGETITLE_Print").': '.$this->escape($this->work['title']); ?>
