<?php $this->headScript()->appendFile($this->makeUrl('/js/tag.js')); ?>

<div id="LRcontainer">
<div class="left-menu">
<?php $flag = 0; ?>
<?php if(!empty($this->work['Interpretations'])): ?>

    <?php foreach($this->work['Interpretations'] as $translation): ?>
    <?php if(isset($translation['work'])): ?>
    
    <?php if($flag == 0): ?><div class="left-section"><?php echo __('Translations'); ?></div><?php endif; ?>
    <?php $flag = 1; ?>
        <span class="translation"><a href="<?php echo $this->url(array('controller'=>'translation','action'=>'read','id'=>$translation['work']['id'])); ?>">
        <?php $title = $this->escape($translation['work']['title']); 
            if($title==''){echo '<i>'.__('No Title').'</i>';} else{echo __($title);} ?>
        </a>(<?php echo __($this->escape($translation['work']['language'])); ?>)</span>
        <br><br>
    <?php endif; ?>
    <?php endforeach; ?>
    
<?php endif; ?>

<?php if($this->isMember){$explainNA=__("You're not allowed to do this. Ask permissions to the text's owner");}
      else{$explainNA=__("You're not allowed to do this. Please login");}
//$a_nohref = 'class="idle" title="'.$explainNA.'"';
$NRattrs = 'class="idle" title="'.$explainNA.'"';
$HTmessage = __("You can't delete this text because it has some translations. Delete its translations first.");?>

<?php $dir = (($this->work['rtl']==1)?'dir="rtl"':''); ?>

<div class="left-section">
    <?php echo __('Options'); ?></div>

    <?php $href= 'href="'.$this->url(array('controller'=>'work','action'=>'translate','id'=>$this->work['id'])).'"';?> 
    <div class="options"><a <?php echo $href.' '.($this->showTranslate?'':$NRattrs); ?>><?php echo __('Create a translation'); ?></a></div><br>
    
    <?php 
        $href_extend= 'href="'.$this->url(array('controller'=>'work','action'=>'extend','id'=>$this->work['id'])).'"';
        $href_edit = 'href="'.$this->url(array('controller'=>'work','action'=>'edit','id'=>$this->work['id'])).'"';
    ?>
    <div class="options"><a <?php echo $href_extend.' '.($this->showEdit?'':$NRattrs); ?>><?php echo __('Continue text insertion'); ?></a></div><br>      
    <div class="options"><a <?php echo $href_edit.' '.($this->showEdit?'':$NRattrs); ?>><?php echo __('Edit the text'); ?></a></div><br>      

    <?php if($this->canManage): ?>
      <div class="options"><a href="<?php echo $this->url(array('controller'=>'work','action'=>'manage','id'=>$this->work['id'])) ?>"><?php echo __("Manage text's privileges"); ?></a></div><br>
    <?php endif; ?>
    
    <?php if($this->canDelete): 
        if($this->hasTranslations==false): 
            $askConfirm = __("WARNING! Deletion is a definitive choice! Are you SURE you want to delete this text?");
            $href= 'href="'.$this->url(array('controller'=>'work','action'=>'delete','id'=>$this->work['id'])).'" onClick="'."return confirm('".$askConfirm."')".'"' ;
        else: $href = 'href="" class="idle" title="'.$HTmessage.'" onClick="alert(\''.addslashes($HTmessage).'\');"'; endif;?>
        <div class = "options"><a <?php echo $href; ?> ><?php echo __("Delete this text"); ?></a></div><br>
    <?endif; ?>
    
    <div class = "options"><a href="<?php echo $this->makeUrl('/work/history/id/'.$this->work['id']); ?>" ><?php echo __("History of modifications"); ?></a></div>

<br><br>

<?php if($this->canTag){echo $this->tagForm; } ?>
</div>

<!--<td id = "right-column">-->
<div class="right-container">
    <div class="show-tag-area" id="show-tag-ajax">
        <?php echo $this->tagbody ?>
    </div>

<div id = "page-container">
<div class = "Tborder"><div class = "TLcorner"></div><div class = "TRcorner"></div></div>
<!--<div id = "Lborder"><img class = "turn-page" src="<?php //echo $this->makeUrl('/images/previous.png'); ?>"></div>-->
        <div class="Lborder hundred"><div class="Rborder hundred">
            <div class = "work-container hundred" <?php echo $dir ?>>
                <div class = "title" id="work-title"><?php $author = ($this->work['author']=='')?__('Anonymous'):$this->work['author'];?>
                <span class="author"><?php echo $author.', ' ?></span>
                <span><?php echo $this->work['title']; ?></span>
                </div>
                
                <div class="language">
                <?php echo __($this->work['language']); ?></div>
                <div class = "text"> 
                    <?php foreach ($this->work['Sentences'] as $segnum=>$sentence) : ?>
                        <?php $segment_id="text".$this->work['id']."-segment".$segnum; ?>
                        <span class="segment" id="<?php echo $segment_id; ?>"><?php echo $this->nlBr($sentence['content']); ?></span>
                    <?php endforeach; ?>
                </div>
                <div class = "creator"> <?php echo (__('Text inserted by')).' ';  echo ($this->work['creator']); ?> </div>
            </div>  
        </div></div>
    
<!--<div id = "Rborder"></div>-->
<div class = "Bborder"><div class = "BLcorner"></div><div class = "BRcorner"></div></div>
</div>
</div>
</div>
<?php $this->page_title = __("PAGETITLE_Read text").': '.$this->escape($this->work['title']); ?>
