
<div id = "left-column"> 
<?php if(isset($this->work['Translations'])): ?>
<div class = "leftColumn-inner">Translations
	<ul>
	<?php foreach($this->work['Translations'] as $translation): ?>
		<li><a href="<?php echo $this->url(array('controller'=>'translation','action'=>'read','id'=>$translation['id'])) ?>">
		<?php echo $this->escape($translation['title']) ?></a></li>
		<?php endforeach; ?>
	</ul>
</div>
<?php endif; ?>
<div class = "leftColumn-inner">Options
	<ul>
	  <li><a href="<?php echo $this->url(array('controller'=>'work','action'=>'translate','id'=>$this->work['id'])) ?>"><?php echo __('Create a Translation'); ?></a></li>
	  <li><a href="<?php echo $this->url(array('controller'=>'work','action'=>'extend','id'=>$this->work['id'])) ?>"><?php echo __('Continue Text Insertion'); ?></a></li>	  
	</ul>
</div>

<?php echo $this->tagForm; ?>
</div>

<div id = "right-column">
	<div class = "title" id="work-title"> <?php echo $this->work['title']; ?> </div>
	<div class = "text"> 
		<?php foreach ($this->work['Sentences'] as $segnum=>$sentence) : ?>
			<?php $segment_id="text".$this->work['id']."-segment".$segnum; ?>
			<span class="segment" id="<?php echo $segment_id; ?>"><?php echo $this->nlBr($sentence['content']); ?></span>
		<?php endforeach; ?>
	</div>
	<div class = "creator"> <?php echo (__('Text inserted by '));  echo $this->work['creator']; ?> </div>
</div>


<?php $this->page_title="Read Text: ".$this->escape($this->work['title']); ?>
