<div id="LRcontainer">
<div class="left-menu">
<?php if(!empty($this->work['Interpretations'])): ?>

    <?php foreach($this->work['Interpretations'] as $translation): ?>
    <?php if(isset($translation['work'])): ?>
    
    <?php if($flag == 0): ?><div class="left-section"><?php echo __('Translations'); ?></div><?php endif; ?>
    <?php $flag = 1; ?>
        <span class="translation"><a href="<?php echo $this->url(array('controller'=>'translation','action'=>'read','id'=>$translation['work']['id'])); ?>">
        <?php echo $this->escape($translation['work']['title']); ?></a>(<?php echo $this->escape($translation['work']['language']); ?>)</span>
        <br><br>
    <?php endif; ?>
    <?php endforeach; ?>
    
<?php endif; ?>

<?php if($this->showCreate || $this->showEdit || $this->canManage): ?>

<div class="left-section">
    <?php echo __('Options'); ?></div>
    <?php if($this->showCreate): ?>
      <div class="options"><a href="<?php echo $this->url(array('controller'=>'work','action'=>'translate','id'=>$this->work['id'])) ?>"><?php echo __('Create a Translation'); ?></a></div><br>
    <?php endif; ?>
    <?php if($this->showEdit): ?>
      <div class="options"><a href="<?php echo $this->url(array('controller'=>'work','action'=>'extend','id'=>$this->work['id'])) ?>"><?php echo __('Continue Text Insertion'); ?></a></div><br>      
    <?php endif; ?>
    <?php if($this->canManage): ?>
      <div class="options"><a href="<?php echo $this->url(array('controller'=>'work','action'=>'manage','id'=>$this->work['id'])) ?>"><?php echo __("Manage Text's Privileges"); ?></a></div><br>
    <?php endif; ?>
    
<?php endif; ?>
<br><br>

<?php if($this->canTag){echo $this->tagForm; } ?>
</div>


<!--<td id = "right-column">-->
<div class="right-container">
 <div class="show-tag-area">
        <?php if(!empty($this->work['Tags'])): ?>
        <?php foreach($this->work['Tags'] as $genre=>$names): ?>
        <?php foreach($names as $name=>$tag): ?>
        <span class="tag-item" title="<?php echo __(strtolower($tag[0]['genre_name'])); ?>"> <!--style="font-size:<?php //echo 8+round($tag['multiplicity']*7) ?>px"--> <?php echo $name; ?>
        <?php $canRemove = false;?>
        <?php foreach($tag as $key=>$elem) {if(is_array($elem)&&(!is_null($this->userid))&&(in_array($this->userid,$elem))){ $canRemove = true;} } ?>
        <?php if($canRemove): ?>
            <a class="delete" href="<?php echo $this->url(array('controller'=>'tag','action'=>'deletetag','id'=>$this->work['id'],'tag'=>$name,'genre'=>$genre))?>"> X </a>
        <?php endif; ?>
        </span>
        <?php endforeach; ?>
        <?php endforeach; ?>
        <?php endif; ?>
    </div>
<div id = "page-container">
<div id = "Tborder"><div id = "TLcorner"></div><div id = "TRcorner"></div></div>
<!--<div id = "Lborder"><img class = "turn-page" src="<?php //echo $this->makeUrl('/images/previous.png'); ?>"></div>-->
        <div id="Lborder" class="hundred"><div id="Rborder" class="hundred">
            <div id = "work-container" class="hundred">
               
                <div class = "title" id="work-title"> <?php echo $this->work['title']; ?> </div>
                <div class="language"><?php $author=$this->work['author']; if($author==''){$author=__('Anonymous');}?>
                <?php echo $author.' - '.__($this->work['language']); ?></div>
                <div class = "text"> 
                    <?php foreach ($this->work['Sentences'] as $segnum=>$sentence) : ?>
                        <?php $segment_id="text".$this->work['id']."-segment".$segnum; ?>
                        <span class="segment" id="<?php echo $segment_id; ?>"><?php echo $this->nlBr($sentence['content']); ?></span>
                    <?php endforeach; ?>
                </div>
                <div class = "creator"> <?php echo (__('Text inserted by')).' ';  echo ($this->work['creator']); ?> </div>
            </div>  
        </div></div>
    
<!--<div id = "Rborder"></div>-->
<div id = "Bborder"><div id = "BLcorner"></div><div id = "BRcorner"></div></div>
</div>
</div>
</div>
<?php $this->page_title = __("Read Text").': '.$this->escape($this->work['title']); ?>
