<?php $elements=$this->form->getElements(); ?>

<div class = "bounding-box">
<div id="warning" class="centered"><?php echo __("Your text will automatically be private.&nbsp; Nobody will be able to see it unless you change the text's privileges.&nbsp;"); ?></div>
    <div id="clear"></div>
    <form action="<?php echo $this->form->getAction() ?>" method="<?php echo $this->form->getMethod() ?>">
        <table class="full-width">
            <tr>    
                <td class="td-left"><div class="title"><?php echo $this->escape($this->origWork['title']); ?></div></td>
                <td class="td-right"><?php echo $elements['title']->render() ?></td>
            </tr>
            <tr>
                <td class="td-left"><div class="language"><?php echo __('Language');?></div></td>
                <td class="td-right"><?php echo $elements['language']->render() ?></td>
            </tr>
            <tr>
                <td></td>
                <td id="button"><?php echo $elements['submit']; ?></div></td>
            </tr>
        </table>
    </form> 
    <div id="clear"></div>
</div>

<?php $this->page_title=__("PAGETITLE_Create Translation of").' '.$this->escape($this->origWork['title']); ?>
