<?php
// application/views/scripts/translation/concord.phtml
?>
<div class="central-home">
<?php $this->headScript()->appendFile($this->makeUrl('/js/filterscroll.js')); ?>
<?php $this->headScript()->appendFile($this->makeUrl('/js/concord.js')); ?>
<?php //echos $this->inlineScript()->appendScript("tdxio.textSearch.current={query:''};tdxio.textSearch.current.filters={}"); ?>
<?php if ($this->style=='pop') $this->layout()->setLayout('nolayout'); ?>
<div id="searchbar">
<form id="form-query"><input name="query" id="query-value" value="<?php echo $this->query; ?>"/>
<input name="srclang" type="hidden" value="<?php echo $this->srclang; ?>"/>
<input name="destlang" type="hidden" value="<?php echo $this->destlang; ?>"/>
<input id="query-submit" type="submit" value="Search"/></form>
</div>
<div id="filters"></div>
<div id="results">
</div>
</div>

<?php $this->page_title="Search"; ?>
