<?php
// application/views/scripts/translation/edit.phtml
/***
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; version 2 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 **/

?>
<?php $this->headLink()->appendStylesheet($this->makeUrl('/css/oldpage.css')) ?>
<?php $this->headScript()->appendFile($this->makeUrl('/js/tag.js')); ?>
<?php $this->headScript()->appendFile($this->makeUrl('/js/traduxio.js')); ?>
<?php $this->headScript()->appendFile($this->makeUrl('/js/autogrow.js')); ?>
<?php $this->headScript()->captureStart(); ?>
tdxio.translation={};
tdxio.translation.id=<?php echo $this->translation['id']; ?>;
tdxio.translation.srcLang = '<?php echo $this->translation['OriginalWork']['language']; ?>';
tdxio.translation.destLang = '<?php echo $this->translation['language']; ?>';
//tdxio.textSearch.current = {filters:{},query:''};
<?php $this->headScript()->captureEnd(); ?>
<?php //if ($this->translation['srcText']['Language']['rtl']) $origDir=' rtl'; else $origDir=""; ?>
<?php //if ($this->translation['Language']['rtl']) $transDir=' rtl'; else $transDir=""; ?>

<?php $elements=$this->form->getElements(); ?>
<form action="<?php echo $this->form->getAction() ?>" method="<?php echo $this->form->getMethod() ?>">

<?php $this->inlineScript()->captureStart(); ?>
if ($.browser.msie) document.write("you may experience display problems with ie, if so use Firefox");
<?php $this->inlineScript()->captureEnd(); ?>
<?php echo $this->inlineScript(); ?>

<?php $tradDir = (($this->translation['rtl']==1)?'dir="rtl"':'');
      $origDir = (($this->translation['OriginalWork']['rtl']==1)?'dir="rtl"':'');
?>    

<div id="LRcontainer">
<!------------------------------------------------------------------------------------------------------------------------>
<table class="new-container full-width">

<tr class="button-line dark">
<td class="w21"></td>
<td></td>
<td class="w21"></td>
<td class="w21"></td>
<td><div class="buttons">
    <?php echo $this->form->buttons; ?>
</div></td>
<td class="w21"></td>
</tr>

<tr class="tag-line dark">
<td class="w21"></td>
<td><div class="show-tag-area">
        <?php if(!empty($this->translation['OriginalWork']['Tags'])): ?>
        <?php foreach($this->translation['OriginalWork']['Tags'] as $genre=>$tags): ?>
        <div class="tag-group">
        <span class="genre"><?php echo __($this->translation['Genres'][$genre]); ?></span>
        <?php foreach($tags as $key=>$tag): ?>
        <span class="tag-item" title="<?php echo __(strtolower($tag['genre_name']));?>"><?php echo $tag['comment']; ?></span>
        <?php endforeach; ?>
        </div>
        <?php endforeach; ?>
        <?php endif; ?>
    </div></td>
<td class="w21"></td>
<td class="w21"></td>
<td><div class="show-tag-area">
        <?php echo $this->tagbody ?>
    </div></td>
<td class="w21"></td>
</tr>

<tr class="full-width">
<td class="w21"><div class="TLcorner w21"></div></td>
<td><div class="Tborder minus1"></div></td>
<td class="w21"><div class="TRcorner w21"></div></td>
<td class="w21"><div class="TLcorner w21"></div></td>
<td><div class="Tborder minus1"></div></td>
<td class="w21"><div class="TRcorner w21"></div></td>
</tr>

<tr class="hundred">
<td class="Lborder w21 hundred"></td>
<td class="whiteback hundred" <?php echo $origDir; ?>>
    <!--<div class = "work-container hundred">-->
        <div class="title">
            <?php $author = $this->translation['OriginalWork']['author']; 
                  $title = $this->escape($this->translation['OriginalWork']['title']);
                  if($author==''){$author=__('Anonymous');} 
                  if($title==''){$author=__('No Title');} ?>
            <span class="author red"><?php echo $author.', ' ?></span>
            <span class="title red"><?php echo $title ?></span>
        </div>
        <div class="language TBspaced red">
            <?php echo __($this->translation['OriginalWork']['language']); ?>
        </div>
    <!--</div>-->
    </td>
<td class="Rborder w21 hundred"></td>
<td class="Lborder w21 hundred"></td>
<td class="whiteback hundred">
    <!--<div class = "work-container hundred">-->
        <div class="title">
            <span class="author"><?php echo $elements['author']->render().'  '  ?></span>
            <span class="author"><?php echo $elements['title']->render()?></span></div>
            <div class="language TBspaced"><?php echo __($this->translation['language']) ?></div>
        <!--</div>-->
    </div>
</td>
<td class="Rborder w21 hundred"></td>
</tr>

<?php foreach ($this->translation['TranslationBlocks'] as $blocknum=>$block) : ?>
<tr>
<td class="Lborder w21 hundred"></td>
<td class="newblock hundred" <?php echo $origDir; ?>><div class="pad10">
<?php foreach ($block['OriginalSentences'] as $segnum=>$segment) : ?>
    <?php $segment = $segment['content']; ?>
    <?php $segment_id="text".$this->translation['OriginalWork']['id']."-segment".$segnum; ?>
    <?php if ($segnum<max(array_keys($block['OriginalSentences']))) {
        $segment=$this->addCutSign($segment,$segnum);
    } else {
        if ($blocknum<max(array_keys($this->translation['TranslationBlocks']))) {
            $segment=$this->addMergeSign($segment,$segnum);
        } else {
            $segment=$this->prepareSegment($segment);
        }
    }?>
    <a name="segment-<?php echo $segnum; ?>"></a>
    <span class="segment" id="<?php echo $segment_id; ?>"><?php echo $segment; ?></span>
<?php endforeach; ?>
</div>
</td>
<td class="Rborder w21 hundred"></td>
<td class="Lborder w21 hundred"></td>
<td class="trablock hundred" <?php echo $tradDir; ?>>
<div  class="pad10"><?php echo $elements['block'.$blocknum]->render(); ?></div>
</td>
<td class="Rborder w21 hundred"></td>
</tr>

<tr class="hundred">
<td class="Lborder w21 hundred"></td>
<td class="whiteback hundred space">
</td>
<td class="Rborder w21 hundred"></td>
<td class="Lborder w21 hundred"></td>
<td class="whiteback hundred space">
</td>
<td class="Rborder w21 hundred"></td>
</tr>

<?php endforeach; ?>

<tr class="h21">
<td class="Lborder w21 hundred"></td>
<td class="whiteback hundred"></td>
<td class="Rborder w21 hundred"></td>
<td class="Lborder w21 hundred"></td>
<td class="whiteback hundred">
    <!--<div class = "work-container hundred">
    </div>-->
</td>
<td class="Rborder w21 hundred"></td>
</tr>

<tr class="full-width">
<td class="BLcorner w21"></td>
<td><div class="Bborder minus1"></div></td>
<td class="w21"><div class="BRcorner w21"></div></td>
<td class="w21"><div class="BLcorner w21"></div></td>
<td><div class="Bborder minus1"></div></td>
<td class="BRcorner w21"></td>
</tr>

<tr class="button-line dark">
<td class="w21"></td>
<td></td>
<td class="w21"></td>
<td class="w21"></td>
<td><div class="buttons">
    <?php echo $this->form->buttons; ?>
</div></td>
<td class="w21"></td>
</tr>

</table>

<!------------------------------------------------------------------------------------------------------------------------>



</form>
<form id="concord-query" action="<?php echo $this->makeUrl('/translation/concord'); ?>" method="post" target="concord" onsubmit="getConcord()">
<input type="hidden" name="query" id="query-value" />
<input type="hidden" name="srclang" value="<?php echo $this->translation['OriginalWork']['language']?>"/>
<input type="hidden" name="destlang" value="<?php echo $this->translation['language']?>"/>
<input type="hidden" name="style" value="pop"/>
</form>
</div>
<?php $this->page_title=__("PAGETITLE_Edit translation").': '.$this->escape($this->translation['title']); ?>

