<?php
// application/views/scripts/text/index.phtml
/***
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; version 2 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 **/

?>
<?php $this->headScript()->appendFile($this->makeUrl('/js/traduxio.js')); ?>
<?php $this->headScript()->appendFile($this->makeUrl('/js/autogrow.js')); ?>
<?php $this->headScript()->captureStart(); ?>
tdxio.translation={};
tdxio.translation.id=<?php echo $this->translation['id']; ?>;
tdxio.translation.srcLang = '<?php echo $this->translation['OriginalWork']['language']; ?>';
tdxio.translation.destLang = '<?php echo $this->translation['language']; ?>';
//tdxio.textSearch.current = {filters:{},query:''};
<?php $this->headScript()->captureEnd(); ?>
<?php //if ($this->translation['srcText']['Language']['rtl']) $origDir=' rtl'; else $origDir=""; ?>
<?php //if ($this->translation['Language']['rtl']) $transDir=' rtl'; else $transDir=""; ?>
<h1><?php echo $this->title ?></h1>
<?php $elements=$this->form->getElements(); ?>
<form action="<?php echo $this->form->getAction() ?>" method="<?php echo $this->form->getMethod() ?>">

<?php $this->inlineScript()->captureStart(); ?>
if ($.browser.msie) document.write("you may experience display problems with ie, if so use Firefox");
<?php $this->inlineScript()->captureEnd(); ?>
<?php echo $this->inlineScript(); ?>
<div class="central-home">
<table class="full-width">
<tr><!--<td class="leftmargin"></td>-->
<td>
<span class="buttons">
<?php echo $this->form->buttons; ?>
</span>
<table class="right-column"><tr>
    <td class="view<?php echo $origDir; ?>"><div class="title">Original text :<?php echo $this->escape($this->translation['OriginalWork']['title']); ?></div></td>
    <td class="edit<?php echo $transDir; ?>"><div class="title">This translation :<?php echo $elements['title']->render() ?></div></td>
</tr>
<?php foreach ($this->translation['InterpretationBlocks'] as $blocknum=>$block) : ?>
<tr>
    <td class="textorig view<?php echo $origDir; ?>">
        <?php $div_id="text".$this->translation['OriginalWork']['id']."-block-".$block['from']."-".$block['to']; ?>
        <div class="block" id="<?php echo $div_id; ?>">
        <?php
            Tdxio_Log::info($block);

            $first=true;
            foreach ($block['OriginalSentences'] as $segnum=>$segment) : ?>
				<?php $segment = $segment['content']; ?>
                <?php $segment_id="text".$this->translation['OriginalWork']['id']."-segment".$segnum; ?>
                <?php if ($segnum<max(array_keys($block['OriginalSentences']))) {
                        $segment=$this->addCutSign($segment,$segnum);
                } else {
                    if ($blocknum<max(array_keys($this->translation['InterpretationBlocks']))) {
                        $segment=$this->addMergeSign($segment,$segnum);
                    } else {
                        $segment=$this->prepareSegment($segment);
                    }
                }?>
                <a name="segment-<?php echo $segnum; ?>"></a>
                <span class="segment" id="<?php echo $segment_id; ?>"><?php echo $segment; ?></span>
        <?php endforeach; ?>
        </div>
    </td>
    <td class="new_translation edit<?php echo $transDir; ?>"><div class="form"><?php echo $elements['block'.$blocknum]->render(); ?></div></td>
</tr>
<?php endforeach; ?>

<tr>
<td><div class="language"><?php //echo $this->escape($this->translation['OriginalWork']['language']['ref_name']);?></div></td>
<td><div class="language"><?php //echo $this->escape($this->translation['language']['ref_name']); ?></div></td>
</tr>
</table>
<span class="buttons">
<?php echo $this->form->buttons; ?>
</span>
</td>

<!--<td class="rightmargin"></td></tr>-->
</table>

</form>
<form id="concord-query" action="<?php echo $this->makeUrl('/translation/concord'); ?>" method="post" target="concord" onsubmit="getConcord()">
<input type="hidden" name="query" id="query-value" />
<input type="hidden" name="srclang" value="<?php echo $this->translation['OriginalWork']['language']?>"/>
<input type="hidden" name="destlang" value="<?php echo $this->translation['language']?>"/>
<input type="hidden" name="style" value="pop"/>
</form>
</div>
<?php //<div id="tdxio-text-div"/> ?>

<?php  $this->page_title="Edit Translation: ".$this->escape($this->translation['title']); ?>
