<?php
// application/views/scripts/translation/edit.phtml
/***
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; version 2 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 **/

?>
<?php $this->headScript()->appendFile($this->makeUrl('/js/traduxio.js')); ?>
<?php $this->headScript()->appendFile($this->makeUrl('/js/autogrow.js')); ?>
<?php $this->headScript()->captureStart(); ?>
tdxio.translation={};
tdxio.translation.id=<?php echo $this->translation['id']; ?>;
tdxio.translation.srcLang = '<?php echo $this->translation['OriginalWork']['language']; ?>';
tdxio.translation.destLang = '<?php echo $this->translation['language']; ?>';
//tdxio.textSearch.current = {filters:{},query:''};
<?php $this->headScript()->captureEnd(); ?>
<?php //if ($this->translation['srcText']['Language']['rtl']) $origDir=' rtl'; else $origDir=""; ?>
<?php //if ($this->translation['Language']['rtl']) $transDir=' rtl'; else $transDir=""; ?>

<?php $elements=$this->form->getElements(); ?>
<form action="<?php echo $this->form->getAction() ?>" method="<?php echo $this->form->getMethod() ?>">

<?php $this->inlineScript()->captureStart(); ?>
if ($.browser.msie) document.write("you may experience display problems with ie, if so use Firefox");
<?php $this->inlineScript()->captureEnd(); ?>
<?php echo $this->inlineScript(); ?>


<div id="LRcontainer">

<table class="right-container" id="openbook-edit">
<tr class="button-line"><td></td><td>
    <div class="buttons">
        <?php echo $this->form->buttons; ?>
    </div>
</td></tr>
<tr class="tag-line">
    <td class="orig-column">   
    <div class="show-tag-area">
        <?php if(!empty($this->translation['OriginalWork']['Tags'])): ?>
        <?php foreach($this->translation['OriginalWork']['Tags'] as $genre=>$names): ?>
        <div class="tag-group">
        <span class="genre"><?php echo __($this->translation['Genres'][$genre]); ?></span>
        <?php foreach($names as $name=>$tag): ?>
        <span class="tag-item" title="<?php echo __(strtolower($tag[0]['genre_name']));?>"><!-- style="font-size:<?php // echo 10+ round($tag['multiplicity']*7) ?>px"> --> <?php echo $name; ?></span>
        <?php endforeach; ?>
        </div>
        <?php endforeach; ?>
        <?php endif; ?>
    </div>
    </td>
    <td class="transl-column">
    <div class="show-tag-area">
        <?php if(!empty($this->translation['Tags'])): ?>
        <?php foreach($this->translation['Tags'] as $genre_name=>$tag_group): ?>  
        <div class="tag-group">
        <span class="genre"><?php echo __($genre_name); ?></span>
        <?php foreach($tag_group as $key=>$tag): ?>  
            <span class="tag-item" title="<?php echo __(strtolower($tag['genre_name'])); ?>"><?php echo $tag['comment']; ?>
            <a class="delete" href="<?php echo $this->url(array('controller'=>'tag','action'=>'deletetag','id'=>$this->translation['id'],'tag'=>$tag['comment'],'genre'=>$tag['genre']))?>"> X </a>
            </span>
        <?php endforeach; ?> 
        </div>
        <?php endforeach; ?> 
        <?php endif; ?>
    </div>
    </td>
    <td></td>
</tr>
<tr class="hundred">
<td class="orig-column hundred" id="Lborder">  
    <div class = "Tborder">
        <div class = "TLcorner"></div><div class = "TRcorner"></div>
    </div>
    <div class="Lborder hundred">
    <div class="Rborder hundred">
        <div class = "work-container hundred">
            <div class="title">
                <span class="author red"><?php echo $this->translation['OriginalWork']['author'].', ' ?></span>
                <span class="title red"><?php echo $this->escape($this->translation['OriginalWork']['title']); ?></span>
            </div>
            <div class="language TBspaced red">
                <?php echo __($this->translation['OriginalWork']['language']); ?>
            </div>
        </div>        
    </div>    
    </div>
</td>

<td class="transl-column hundred">

        <div class = "Tborder">
            <div class = "TLcorner"></div><div class = "TRcorner"></div>
        </div>
        <div class="Lborder hundred">
        <div class="Rborder hundred">
            <div class = "work-container hundred">
                <div class="title">
                <span class="author"><?php echo $elements['author']->render().'  '  ?></span>
                <span class="author"><?php echo $elements['title']->render()?></span></div>
                <div class="language TBspaced"><?php echo __($this->translation['language']) ?></div>
                
            </div>
        </div>
        </div>
</td>
</tr>

<?php foreach ($this->translation['TranslationBlocks'] as $blocknum=>$block) : ?>

<tr class="hundred">
    <td class="orig-column hundred Lborder">
        <div class="Lborder hundred">
        <div class="Rborder hundred">
        <div class = "work-container upperblock hundred">        
        <div class="block" id="<?php echo $div_id; ?>">
        <?php
        Tdxio_Log::info($block);

        $first=true;
        foreach ($block['OriginalSentences'] as $segnum=>$segment) : ?>
            <?php $segment = $segment['content']; ?>
            <?php $segment_id="text".$this->translation['OriginalWork']['id']."-segment".$segnum; ?>
            <?php if ($segnum<max(array_keys($block['OriginalSentences']))) {
                    $segment=$this->addCutSign($segment,$segnum);
            } else {
                if ($blocknum<max(array_keys($this->translation['TranslationBlocks']))) {
                    $segment=$this->addMergeSign($segment,$segnum);
                } else {
                    $segment=$this->prepareSegment($segment);
                }
            }?>
            <a name="segment-<?php echo $segnum; ?>"></a>
            <span class="segment" id="<?php echo $segment_id; ?>"><?php echo $segment; ?></span>
        <?php endforeach; ?>
        </div>
        </div>
        </div>
        </div>
    </td>
    
    <td class="transl-column hundred edit<?php echo $transDir; ?>">
        <div class="Lborder hundred">
        <div class="Rborder hundred">
        <div class = "work-container hundred">        
    
        <div class="form"><?php echo $elements['block'.$blocknum]->render(); ?></div>
    
        </div>
        </div>
        </div>
    </td>
</tr>

<!--
<tr>
<td> 
    <div class="Lborder">
        <div class="Rborder">
            <div class = "space-container">
            <br>
            </div>
        </div>
    </div>
</td>
<td>
    <div class="Lborder">
        <div class="Rborder">
            <div class = "space-container">
            <br>  
            </div>
        </div>
    </div>
</td>
</tr>
-->
<?php endforeach; ?>

<tr class="hundred">
    <td class="orig-column hundred Lborder">
     <div class="Lborder hundred">
        <div class="Rborder hundred">
        <div class = "work-container hundred">    </div>
        </div></div>
        <div class = "Bborder">
        <div class = "BLcorner"></div><div class = "BRcorner"></div>
        </div>
    </td>
    <td class="transl-column hundred">
    <div class="Lborder hundred">
        <div class="Rborder hundred">
         <div class = "work-container hundred">    </div>
        </div></div>
        <div class = "Bborder">
        <div class = "BLcorner"></div><div class = "BRcorner"></div>
        </div>
    </td>
</tr>
<tr><td colspan="2" class="bottom-spacer"></td></tr>

<tr class = "button-line"><td></td><td>
<div class="buttons">
<?php echo $this->form->buttons; ?>
</div>
</td></tr>




</table>
</form>
<form id="concord-query" action="<?php echo $this->makeUrl('/translation/concord'); ?>" method="post" target="concord" onsubmit="getConcord()">
<input type="hidden" name="query" id="query-value" />
<input type="hidden" name="srclang" value="<?php echo $this->translation['OriginalWork']['language']?>"/>
<input type="hidden" name="destlang" value="<?php echo $this->translation['language']?>"/>
<input type="hidden" name="style" value="pop"/>
</form>
</div>
<?php $this->page_title=__("PAGETITLE_Edit translation").': '.$this->escape($this->translation['title']); ?>

