<div class="central-home">
<table class="full-width">
<tr>
<td class="left-column"> 
<?php if($this->showEdit || $this->canManage): ?>
<div class="left-section"><?php echo __('Options'); ?></div>
    
        <?php if($this->showEdit): ?>
            <div class="options"><a href="<?php echo $this->url(array('controller'=>'translation','action'=>'edit','id'=>$this->translation['id'])) ?>"><?php echo __('Edit this Translation'); ?></a></div>      
            <br>
        <?php endif; ?>
        <?php if($this->canManage): ?>
            <div class="options"><a href="<?php echo $this->url(array('controller'=>'work','action'=>'manage','id'=>$this->translation['id'])) ?>"><?php echo __("Manage Text's privileges"); ?></a></div>    
        <?php endif; ?>
<?php endif; ?>
<br><br>
<div id="tag-area">
<?php if($this->canTag){echo $this->tagForm; } ?>
</div>
</td>

<td class="top-align">
<table  class="right-column">
<tr class="up-section"><td> <div id="tag-area">
        <?php if(!empty($this->translation['OriginalWork']['Tags'])): ?>
        <?php foreach($this->translation['OriginalWork']['Tags'] as $tag): ?>
        <div class="tag-item" style="font-size:<?php echo 10+ round($tag['multiplicity']*7) ?>px"><?php echo $tag[0]['comment']; ?></div>
        <?php endforeach; ?>
        <?php endif; ?>
    </div></td><td>   <div id="tag-area">
        <?php if(!empty($this->translation['Tags'])): ?>
        <?php foreach($this->translation['Tags'] as $name=>$tag): ?>        
            <div class="tag-item" style="font-size:<?php echo 10+ round($tag['multiplicity']*7) ?>px"><?php echo $tag[0]['comment']; ?>
            <?php $canRemove = false;?>
            <?php foreach($tag as $key=>$elem) {if(is_array($elem)&&(!is_null($this->userid))&&(in_array($this->userid,$elem))){ $canRemove = true;} } ?>
            <?php if($canRemove): ?>
                <a class="delete" href="<?php echo $this->url(array('controller'=>'tag','action'=>'deletetag','id'=>$this->translation['id'],'tag'=>$name))?>"> X </a>
            <?php endif; ?>
            </div>
        <?php endforeach; ?>
        <?php endif; ?>
    </div></td>
</tr>
<tr><td  class="right-column">
   
    <div class="title"><?php echo __('Original Text').': ' ?><a href="<?php echo $this->url(array('controller'=>'work','action'=>'read','id'=>$this->translation['OriginalWorkId'])) ?>"><?php echo $this->translation['OriginalWork']['title']; ?></a></div>
    <div class="language"><?php echo __($this->translation['OriginalWork']['language']); ?></div>
    <div class="original-text"><?php foreach($this->translation['OriginalSentences'] as $key=>$sentence): ?>
                     <?php echo $sentence['content']; ?>
                     <?php endforeach; ?>
    </div>
</td>
<td  class="right-column"> 

 
    <div class="title"><?php echo __('Translation').': '?><?php echo $this->translation['title']; ?></div>
    <div class="language"><?php echo __($this->translation['language']); ?></div>
    <div class="translated-text"><?php foreach($this->translation['TranslationBlocks'] as $key=>$block): ?>
                     <?php echo $block['translation']; ?>
                     <?php endforeach; ?>
</div>
</td>

</tr>
</table>

</td>
</tr>
</table>
</div>
<?php $this->page_title=__("Read Translation").': '.$this->escape($this->translation['title']); ?>

