<div id="LRcontainer">
<div class="left-menu">
<?php if($this->showEdit || $this->canManage): ?>
<div class="left-section"><?php echo __('Options'); ?></div>
    
        <?php if($this->showEdit): ?>
            <div class="options"><a href="<?php echo $this->url(array('controller'=>'translation','action'=>'edit','id'=>$this->translation['id'])) ?>"><?php echo __('Edit this Translation'); ?></a></div>      
            <br>
        <?php endif; ?>
        <?php if($this->canManage): ?>
            <div class="options"><a href="<?php echo $this->url(array('controller'=>'work','action'=>'manage','id'=>$this->translation['id'])) ?>"><?php echo __("Manage Text's privileges"); ?></a></div>    
        <?php endif; ?>
<?php endif; ?>
<br><br>
<div id="tag-area">
<?php if($this->canTag){echo $this->tagForm; } ?>
</div>
</div>


<table class="right-container" id="openbook-read">
<tr class="tag-line">
    <td class="orig-column">   
    <div class="show-tag-area">
        <?php if(!empty($this->translation['OriginalWork']['Tags'])): ?>
        <?php foreach($this->translation['OriginalWork']['Tags'] as $genre=>$names): ?>
        <div class="tag-group">
        <span class="genre"><?php echo __($this->translation['Genres'][$genre]); ?></span>
        <?php foreach($names as $name=>$tag): ?>
        <span class="tag-item" title="<?php echo __(strtolower($tag[0]['genre_name']));?>"><!-- style="font-size:<?php // echo 10+ round($tag['multiplicity']*7) ?>px"> --> <?php echo $name; ?></span>
        <?php endforeach; ?>
        </div>
        <?php endforeach; ?>
        <?php endif; ?>
    </div>
    </td>
    <td class="transl-column">
    <div class="show-tag-area">
        <?php if(!empty($this->translation['Tags'])): ?>
        <?php foreach($this->translation['Tags'] as $genre=>$names): ?>  
        <div class="tag-group">
        <span class="genre"><?php echo __($this->translation['Genres'][$genre]); ?></span>
        <?php foreach($names as $name=>$tag): ?>      
            <span class="tag-item" title="<?php echo __(strtolower($tag[0]['genre_name'])); ?>" style="font-size:<?php echo 8+ round($tag['multiplicity']*7) ?>px"><?php echo $name; ?>
            <?php $canRemove = false;?>
            <?php foreach($tag as $key=>$elem) {if(is_array($elem)&&(!is_null($this->userid))&&(in_array($this->userid,$elem))){ $canRemove = true;} } ?>
            <?php if($canRemove): ?>
                <a class="delete" href="<?php echo $this->url(array('controller'=>'tag','action'=>'deletetag','id'=>$this->translation['id'],'tag'=>$name,'genre'=>$genre))?>"> X </a>
            <?php endif; ?>
            </span>
        <?php endforeach; ?>        
        </div>
        <?php endforeach; ?>
        <?php endif; ?>
    </div>
    </td>
</tr>
<tr class="hundred">
<td class="orig-column hundred Lborder"> 
<!--  
<div id="original-text-page">-->
 
        <div class = "Tborder">
            <div class = "TLcorner"></div><div class = "TRcorner"></div>
        </div>
        <div class="Lborder hundred"><div class="Rborder hundred">
            <div class = "work-container hundred">
                <div class="title"><?php echo __('Original Text').': ' ?><a href="<?php echo $this->url(array('controller'=>'work','action'=>'read','id'=>$this->translation['OriginalWorkId'])) ?>"><?php echo $this->translation['OriginalWork']['title']; ?></a></div>
                <div class="language">
                <?php $author = $this->translation['OriginalWork']['author']; if($author==''){$author=__('Anonymous');}?>
                <?php echo $author.' - '.__($this->translation['OriginalWork']['language']); ?></div>
                <div class="text"><?php foreach($this->translation['OriginalSentences'] as $key=>$sentence): ?>
                                 <?php echo $sentence['content']; ?>
                                 <?php endforeach; ?>
                </div>
                <div class = "creator"> <?php echo (__('Text inserted by')).' ';  echo ($this->translation['OriginalWork']['creator']); ?> </div>
            </div>        
        </div></div>
        <div class = "Bborder">
            <div class = "BLcorner"></div><div class = "BRcorner"></div>
        </div>
<!--</div>-->
</td>

<td class="transl-column hundred">

        <div class = "Tborder">
            <div class = "TLcorner"></div><div class = "TRcorner"></div>
        </div>
        <!--<div id = "Lborder"><img class = "turn-page" src="<?php //echo $this->makeUrl('/images/previous.png'); ?>"></div>-->
        <div class="Lborder hundred"><div class="Rborder hundred">
            <div class = "work-container hundred">
                <div class="title"><?php echo __('Translation').': '?>
                <?php $title = $this->escape($this->translation['title']);if($title==''){echo '<i>'.__('No Title').'</i>';} else{echo __($title);} ?>
                </div>
                <div class="language">
                <?php $author = $this->translation['author']; if($author==''){$author=__('Anonymous');}?>
                <?php echo $author.' - '.__($this->translation['language']); ?></div>
                <div class="text"><?php foreach($this->translation['TranslationBlocks'] as $key=>$block): ?>
                                 <?php echo $block['translation']; ?>
                                 <?php endforeach; ?>
                </div>
                <div class = "creator"> <?php echo (__('Text inserted by')).' ';  echo ($this->translation['creator']); ?> </div>
            </div>
        </div></div>
        <div class = "Bborder">
            <div class = "BLcorner"></div><div class = "BRcorner"></div>
        </div>

</td>
</tr><tr><td colspan="2" class="bottom-spacer"></td></tr>
</table>
</div>

<?php $this->page_title=__("Read Translation").': '.$this->escape($this->translation['title']); ?>
